'use strict';
const cfgModule=require('./facebook-config');const {classifyProviderError,POST_ID}=require('./facebook-publishing');const {safeError}=require('./errors');const {resolveSelectedPageCredential}=require('./facebook-page-credential');
const MAX_BODY=65536,TIMEOUT_MS=8000;
function fail(code,id,extra={}){return{ok:false,error:safeError(code,id),...extra};}
async function request(url,options={},deps={}){const fetchImpl=deps.fetchImpl||globalThis.fetch,c=new AbortController(),timer=setTimeout(()=>c.abort(),deps.timeoutMs||TIMEOUT_MS);try{const response=await fetchImpl(url,{...options,signal:c.signal});const text=await response.text();if(Buffer.byteLength(text)>MAX_BODY)return fail('facebook_response_invalid');let body;try{body=JSON.parse(text);}catch{return fail(response.ok?'facebook_response_invalid':'provider_transient_failure');}if(!response.ok){const oauthCode=Number(body?.error?.code);return fail(classifyProviderError(response.status,oauthCode),null,{httpStatus:response.status,providerOAuthCategory:Number.isSafeInteger(oauthCode)&&oauthCode>=0&&oauthCode<=10000?`oauth_${oauthCode}`:null});}return{ok:true,value:body};}catch{return fail('provider_ambiguous_result');}finally{clearTimeout(timer);}}
function createFacebookAdapter({env=process.env,fetchImpl=globalThis.fetch}={}){const cfg=()=>cfgModule.load(env);return Object.assign(Object.create(null),{capabilities:['getAuthorizationRequest','exchangeAuthorizationCode','discoverAccount','discoverPermissions','discoverDestinations','facebook_page_text_link_publish_v1','facebook_post_engagement_read_v1'],
 async getAuthorizationRequest({context,input}){const c=cfg();if(!c.ready)return fail('facebook_not_configured',context.requestId);const u=new URL(cfgModule.AUTHORIZATION_ENDPOINT);u.search=new URLSearchParams({client_id:c.appId,redirect_uri:c.redirectUri,state:input.state,response_type:'code',scope:c.scopes.join(',')}).toString();return{ok:true,value:{authorizationUrl:u.toString(),requestedScopes:c.scopes,redirectUri:c.redirectUri}};},
 async exchangeAuthorizationCode({context,input}){const c=cfg();if(typeof input.code!=='string'||input.code.length<2||input.code.length>2048)return fail('facebook_code_missing',context.requestId);const u=new URL(cfgModule.TOKEN_ENDPOINT);u.search=new URLSearchParams({client_id:c.appId,client_secret:c.appSecret,redirect_uri:c.redirectUri,code:input.code}).toString();const r=await request(u,{headers:{accept:'application/json'}},{fetchImpl});if(!r.ok)return r;const v=r.value;if(typeof v.access_token!=='string'||v.access_token.length<8||v.access_token.length>12000)return fail('facebook_response_invalid');return{ok:true,value:{credential:{accessToken:v.access_token,pageTokens:{}},grantedScopes:[...c.scopes],expiresAt:Number.isFinite(v.expires_in)?new Date(Date.now()+v.expires_in*1000).toISOString():null}};},
 async discoverAccount({context,credentials}){const u=new URL(`${cfgModule.GRAPH_ENDPOINT}/me`);u.searchParams.set('fields','id,name');const r=await request(u,{headers:{accept:'application/json',authorization:`Bearer ${credentials.accessToken}`}},{fetchImpl});if(!r.ok)return r;return typeof r.value.id==='string'&&typeof r.value.name==='string'?{ok:true,value:{externalAccountId:r.value.id,displayName:r.value.name,accountType:'user'}}:fail('facebook_identity_missing',context.requestId);},
 async discoverPermissions({context,credentials}){const u=new URL(`${cfgModule.GRAPH_ENDPOINT}/me/permissions`);const r=await request(u,{headers:{accept:'application/json',authorization:`Bearer ${credentials.accessToken}`}},{fetchImpl});if(!r.ok)return r;const granted=(Array.isArray(r.value.data)?r.value.data:[]).filter(x=>x?.status==='granted'&&typeof x.permission==='string').map(x=>x.permission);return{ok:true,value:[...new Set(granted)]};},
 async discoverDestinations({context,credentials}){const u=new URL(`${cfgModule.GRAPH_ENDPOINT}/me/accounts`);u.searchParams.set('fields','id,name,tasks,access_token');const r=await request(u,{headers:{accept:'application/json',authorization:`Bearer ${credentials.accessToken}`}},{fetchImpl});if(!r.ok)return r;const pages=Array.isArray(r.value.data)?r.value.data:[],value=pages.filter(p=>typeof p.id==='string'&&typeof p.name==='string'&&Array.isArray(p.tasks)&&p.tasks.includes('CREATE_CONTENT')&&typeof p.access_token==='string').map(p=>({externalDestinationId:p.id,type:'page',displayName:p.name,capabilities:[...new Set(p.tasks.filter(x=>typeof x==='string'&&x.length<=64))],pageAccessToken:p.access_token}));return{ok:true,value,pageCount:pages.length};},
 async facebook_page_text_link_publish_v1({context,credentials,input}){const selected=resolveSelectedPageCredential(credentials,input.pageId);if(!selected)return fail('credential_invalid',context.requestId);const token=selected.accessToken;const body=new URLSearchParams({message:input.message,access_token:token});if(input.link)body.set('link',input.link);let r=await request(`${cfgModule.GRAPH_ENDPOINT}/${encodeURIComponent(input.pageId)}/feed`,{method:'POST',headers:{'content-type':'application/x-www-form-urlencoded',accept:'application/json'},body},{fetchImpl});if(!r.ok)return r.error?.code==='provider_ambiguous_result'?{...r,acceptanceKnown:false}:r;const id=String(r.value.id||'');if(!POST_ID.test(id))return fail('provider_ambiguous_result',context.requestId,{acceptanceKnown:true});let permalink=null;const get=new URL(`${cfgModule.GRAPH_ENDPOINT}/${encodeURIComponent(id)}`);get.searchParams.set('fields','permalink_url');const read=await request(get,{headers:{accept:'application/json',authorization:`Bearer ${token}`}},{fetchImpl});if(read.ok&&typeof read.value.permalink_url==='string'){try{const u=new URL(read.value.permalink_url);if(u.protocol==='https:'&&/^(?:www\.)?facebook\.com$/i.test(u.hostname))permalink=u.toString();}catch{}}return{ok:true,value:{postId:id,permalink}};},
 async facebook_post_engagement_read_v1(argument){const context=argument?.context,input=argument?.input,credential=argument?.credential,keys=value=>value&&typeof value==='object'&&!Array.isArray(value)?Object.keys(value).sort():[];const valid=argument&&typeof argument==='object'&&!Array.isArray(argument)&&JSON.stringify(keys(argument))===JSON.stringify(['context','credential','input'])&&JSON.stringify(keys(credential))===JSON.stringify(['accessToken','tokenSource'])&&credential.tokenSource==='selected_page_token'&&typeof credential.accessToken==='string'&&credential.accessToken.length>=8&&credential.accessToken.length<=12000&&credential.accessToken===credential.accessToken.trim();if(!valid)return fail('credential_invalid',context?.requestId,{adapterArgumentValidity:'invalid',outboundTokenType:typeof credential?.accessToken,outboundTokenPresence:typeof credential?.accessToken==='string'&&credential.accessToken.length>0});const token=credential.accessToken;if(!POST_ID.test(input?.postId||''))return fail('facebook_response_invalid',context?.requestId,{adapterArgumentValidity:'valid',outboundTokenType:'string',outboundTokenPresence:true});const read=async fields=>{const url=new URL(`${cfgModule.GRAPH_ENDPOINT}/${encodeURIComponent(input.postId)}`);url.searchParams.set('fields',fields);return request(url,{method:'GET',headers:{accept:'application/json',authorization:`Bearer ${token}`}},{fetchImpl});};const result=await read('reactions.limit(0).summary(true),comments.limit(0).summary(true),shares');if(result.ok)return result;if(result.providerOAuthCategory==='oauth_10'){const minimum=await read('reactions.limit(0).summary(true)');if(minimum.ok)return{ok:true,value:minimum.value,partialResultCategory:'optional_metrics_permission_unavailable',failedMetricCategory:'comments_and_shares'};}return{...result,adapterArgumentValidity:'valid',outboundTokenType:'string',outboundTokenPresence:true};}
 });}
module.exports={MAX_BODY,TIMEOUT_MS,request,createFacebookAdapter};
