'use strict';
const crypto=require('crypto'),oauth=require('./oauth-state'),vault=require('./token-vault'),config=require('./facebook-config');
const {createFacebookAdapter}=require('./facebook-adapter');const linked=require('./linkedin-service');
const hash=linked.hash,sessionFingerprint=linked.sessionFingerprint,requestId=linked.requestId,accountId=linked.accountId;
const REASONS=Object.freeze({token_exchange:'facebook_token_exchange_failed',permissions:'facebook_permissions_missing',identity:'facebook_identity_failed',pages:'facebook_pages_failed',eligible_pages:'facebook_no_eligible_pages',encryption:'facebook_credential_encryption_failed',account_persistence:'facebook_account_persistence_failed',destination_persistence:'facebook_destination_persistence_failed'});
function diagnostic(code,stage,id,details={}){return{code,stage,correlationId:id,retryable:false,httpStatus:Number.isInteger(details.httpStatus)?details.httpStatus:undefined,requiredScopesPresent:typeof details.requiredScopesPresent==='boolean'?details.requiredScopesPresent:undefined,pageCount:Number.isInteger(details.pageCount)?details.pageCount:undefined,eligiblePageCount:Number.isInteger(details.eligiblePageCount)?details.eligiblePageCount:undefined,databaseCode:/^[0-9A-Z]{5}$/.test(details.databaseCode||'')?details.databaseCode:undefined,constraint:/^[a-z][a-z0-9_]{0,62}$/.test(details.constraint||'')?details.constraint:undefined};}
function failure(code,stage,x,details){return{ok:false,error:diagnostic(code,stage,x.serverRequestId,details),attemptId:x.attemptId};}
function outcome(code){if(code==='success')return'facebook_connected';if(code==='facebook_authorization_denied')return'facebook_cancelled';const safe=new Set(['facebook_state_invalid','facebook_session_invalid',...Object.values(REASONS),'facebook_connection_failed']);return safe.has(code)?code:'facebook_connection_failed';}
function adapterFailure(stage,result,x,details={}){return failure(REASONS[stage],stage,x,{...details,httpStatus:result?.httpStatus||result?.error?.httpStatus});}
function createService({pool,env=process.env,fetchImpl}={}){const adapter=createFacebookAdapter({env,fetchImpl});
 async function start(x){const c=config.load(env);if(!c.ready)return failure('facebook_connection_failed','start',x);const a=oauth.create({ownerAccountId:x.ownerAccountId,platform:'facebook',returnPath:'/',sessionFingerprint:x.sessionBinding}),id=crypto.randomUUID();await pool.query('INSERT INTO public.social_oauth_attempts(id,owner_account_id,platform,return_path,state_hash,session_binding_fingerprint,client_request_id,server_request_id,last_confirmed_phase,created_at,expires_at) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11)',[id,x.ownerAccountId,'facebook','/',hash(a.state),x.sessionBinding,x.clientRequestId||null,x.serverRequestId,'state_received',a.createdAt,a.expiresAt]);const auth=await adapter.getAuthorizationRequest({context:{requestId:x.serverRequestId,accountId:x.ownerAccountId},input:{state:a.state}});return auth.ok?{ok:true,value:{authorizationUrl:auth.value.authorizationUrl,expiresAt:a.expiresAt,serverRequestId:x.serverRequestId}}:auth;}
 async function complete(x){if(!x.state)return failure('facebook_state_invalid','state_lookup',x);const stateClient=await pool.connect();let attempt;
  try{await stateClient.query('BEGIN');attempt=(await stateClient.query('SELECT * FROM public.social_oauth_attempts WHERE state_hash=$1 FOR UPDATE',[hash(x.state)])).rows[0];if(!attempt||attempt.consumed_at||attempt.owner_account_id!==x.ownerAccountId||attempt.platform!=='facebook'||attempt.session_binding_fingerprint!==x.sessionBinding){await stateClient.query('ROLLBACK');return failure('facebook_state_invalid','state_ownership',x);}x.attemptId=attempt.id;if(Date.now()>=Date.parse(attempt.expires_at)){await stateClient.query("UPDATE public.social_oauth_attempts SET consumed_at=NOW(),failure_classification='facebook_state_expired' WHERE id=$1",[attempt.id]);await stateClient.query('COMMIT');return failure('facebook_state_invalid','state_expired',x);}await stateClient.query('UPDATE public.social_oauth_attempts SET consumed_at=NOW(),last_confirmed_phase=$2 WHERE id=$1',[attempt.id,'state_consumed']);await stateClient.query('COMMIT');}
  catch(error){await stateClient.query('ROLLBACK').catch(()=>{});return failure('facebook_connection_failed','state_persistence',x,{databaseCode:error?.code,constraint:error?.constraint});}finally{stateClient.release();}
  if(!x.code)return failure('facebook_authorization_denied','authorization_code',x);
  const ctx={requestId:x.serverRequestId,accountId:x.ownerAccountId};
  const token=await adapter.exchangeAuthorizationCode({context:ctx,input:{code:x.code}});if(!token.ok)return adapterFailure('token_exchange',token,x);
  const permissions=await adapter.discoverPermissions({context:ctx,credentials:token.value.credential});if(!permissions.ok)return adapterFailure('permissions',permissions,x,{requiredScopesPresent:false});
  token.value.grantedScopes=permissions.value.filter(scope=>config.SCOPES.includes(scope));const scopesPresent=config.SCOPES.every(scope=>token.value.grantedScopes.includes(scope));if(!scopesPresent)return failure(REASONS.permissions,'permissions',x,{requiredScopesPresent:false});
  const identity=await adapter.discoverAccount({context:ctx,credentials:token.value.credential});if(!identity.ok)return adapterFailure('identity',identity,x,{requiredScopesPresent:true});
  const discovered=await adapter.discoverDestinations({context:ctx,credentials:token.value.credential});if(!discovered.ok)return adapterFailure('pages',discovered,x,{requiredScopesPresent:true});
  const pageCount=Number.isInteger(discovered.pageCount)?discovered.pageCount:discovered.value.length,eligiblePageCount=discovered.value.length;if(!eligiblePageCount)return failure(REASONS.eligible_pages,'eligible_pages',x,{requiredScopesPresent:true,pageCount,eligiblePageCount});
  discovered.value.forEach(page=>{token.value.credential.pageTokens[page.externalDestinationId]=page.pageAccessToken;delete page.pageAccessToken;});
  let secretId,sealed;try{secretId=crypto.randomUUID();sealed=vault.seal(token.value.credential,{secretId,ownerAccountId:x.ownerAccountId,platform:'facebook'},{keyVersion:config.load(env).keyVersion,env});}catch{return failure(REASONS.encryption,'encryption',x,{requiredScopesPresent:true,pageCount,eligiblePageCount});}
  const writer=await pool.connect();let stage='account_persistence';try{await writer.query('BEGIN');const old=(await writer.query("SELECT id,token_secret_id FROM public.social_connected_accounts WHERE owner_account_id=$1 AND platform='facebook' AND status<>'disconnected' FOR UPDATE",[x.ownerAccountId])).rows[0];await writer.query("INSERT INTO public.social_token_secrets(id,owner_account_id,platform,encrypted_payload,nonce,authentication_tag,encryption_key_version) VALUES($1,$2,'facebook',$3,$4,$5,$6)",[secretId,x.ownerAccountId,sealed.ciphertext,sealed.nonce,sealed.authenticationTag,sealed.keyVersion]);const up=(await writer.query("INSERT INTO public.social_connected_accounts(owner_account_id,platform,external_account_id,external_display_name,account_type,status,granted_scopes,token_secret_id,token_expires_at,last_validated_at,last_oauth_attempt_id) VALUES($1,'facebook',$2,$3,'user','connected',$4,$5,$6,NOW(),$7) ON CONFLICT(owner_account_id,platform,external_account_id) WHERE external_account_id IS NOT NULL DO UPDATE SET external_display_name=EXCLUDED.external_display_name,status='connected',granted_scopes=EXCLUDED.granted_scopes,token_secret_id=EXCLUDED.token_secret_id,token_expires_at=EXCLUDED.token_expires_at,last_validated_at=NOW(),last_oauth_attempt_id=EXCLUDED.last_oauth_attempt_id,updated_at=NOW(),disconnected_at=NULL RETURNING id",[x.ownerAccountId,identity.value.externalAccountId,identity.value.displayName,JSON.stringify(token.value.grantedScopes),secretId,token.value.expiresAt,attempt.id])).rows[0];stage='destination_persistence';await writer.query("UPDATE public.social_publishing_destinations SET active=FALSE,status='unavailable',updated_at=NOW() WHERE connected_account_id=$1 AND owner_account_id=$2",[up.id,x.ownerAccountId]);const autoSelect=eligiblePageCount===1;for(const page of discovered.value)await writer.query("INSERT INTO public.social_publishing_destinations(connected_account_id,owner_account_id,external_destination_id,destination_type,display_name,capabilities,authorization_state,status,active,last_capability_refresh_at) VALUES($1,$2,$3,'page',$4,$5,'authorized','active',$6,NOW()) ON CONFLICT(connected_account_id,external_destination_id) DO UPDATE SET display_name=EXCLUDED.display_name,capabilities=EXCLUDED.capabilities,authorization_state='authorized',status='active',active=EXCLUDED.active,last_capability_refresh_at=NOW(),updated_at=NOW()",[up.id,x.ownerAccountId,page.externalDestinationId,page.displayName,JSON.stringify(page.capabilities),autoSelect]);if(old?.token_secret_id&&old.token_secret_id!==secretId)await writer.query('UPDATE public.social_token_secrets SET revoked_at=NOW(),updated_at=NOW() WHERE id=$1',[old.token_secret_id]);await writer.query('COMMIT');return{ok:true,value:{result:'success',attemptId:attempt.id,eligiblePageCount,selectedDestination:autoSelect}};
  }catch(error){await writer.query('ROLLBACK').catch(()=>{});return failure(REASONS[stage],stage,x,{requiredScopesPresent:true,pageCount,eligiblePageCount,databaseCode:error?.code,constraint:error?.constraint});}finally{writer.release();}}
 async function disconnect(x){const c=await pool.connect();try{await c.query('BEGIN');const row=(await c.query("SELECT id,token_secret_id FROM public.social_connected_accounts WHERE id=$1 AND owner_account_id=$2 AND platform='facebook' FOR UPDATE",[x.connectionId,x.ownerAccountId])).rows[0];if(!row){await c.query('ROLLBACK');return failure('facebook_connection_failed','disconnect',x);}await c.query('UPDATE public.social_token_secrets SET revoked_at=NOW(),updated_at=NOW() WHERE id=$1 AND owner_account_id=$2',[row.token_secret_id,x.ownerAccountId]);await c.query("UPDATE public.social_connected_accounts SET status='disconnected',disconnected_at=NOW(),updated_at=NOW() WHERE id=$1",[row.id]);await c.query("UPDATE public.social_publishing_destinations SET active=FALSE,status='unauthorized',updated_at=NOW() WHERE connected_account_id=$1 AND owner_account_id=$2",[row.id,x.ownerAccountId]);await c.query('COMMIT');return{ok:true,value:{state:'disconnected',connectionId:row.id}};}catch{await c.query('ROLLBACK').catch(()=>{});return failure('facebook_connection_failed','disconnect',x);}finally{c.release();}}
 async function selectDestination(x){if(!/^[0-9a-f-]{36}$/i.test(x.destinationId||''))return failure('facebook_destination_invalid','destination_selection',x);const c=await pool.connect();try{await c.query('BEGIN');const connection=(await c.query("SELECT c.id,c.token_secret_id,c.granted_scopes,c.token_expires_at,s.id AS secret_id,s.revoked_at FROM public.social_connected_accounts c JOIN public.social_token_secrets s ON s.id=c.token_secret_id AND s.owner_account_id=c.owner_account_id AND s.platform=c.platform WHERE c.owner_account_id=$1 AND c.platform='facebook' AND c.status='connected' AND c.disconnected_at IS NULL FOR UPDATE",[x.ownerAccountId])).rows[0],required=config.SCOPES;if(!connection||!connection.secret_id||connection.revoked_at||(connection.token_expires_at&&Date.parse(connection.token_expires_at)<=Date.now())||!required.every(scope=>(connection.granted_scopes||[]).includes(scope))){await c.query('ROLLBACK');return failure('facebook_connection_unavailable','destination_selection',x);}const destination=(await c.query("SELECT id,connected_account_id,display_name,destination_type,capabilities,authorization_state,status FROM public.social_publishing_destinations WHERE id=$1 AND owner_account_id=$2 FOR UPDATE",[x.destinationId,x.ownerAccountId])).rows[0];if(!destination||destination.connected_account_id!==connection.id||destination.destination_type!=='page'||destination.authorization_state!=='authorized'||destination.status!=='active'||!Array.isArray(destination.capabilities)||!destination.capabilities.includes('CREATE_CONTENT')){await c.query('ROLLBACK');return failure('facebook_destination_ineligible','destination_selection',x);}await c.query("UPDATE public.social_publishing_destinations SET active=(id=$1),updated_at=CASE WHEN active<>(id=$1) THEN NOW() ELSE updated_at END WHERE connected_account_id=$2 AND owner_account_id=$3",[destination.id,connection.id,x.ownerAccountId]);await c.query('COMMIT');return{ok:true,value:{connectionId:connection.id,destination:{id:destination.id,label:destination.display_name,type:'page',capabilities:['CREATE_CONTENT'],selected:true}}};}catch(error){await c.query('ROLLBACK').catch(()=>{});return failure('facebook_destination_persistence_failed','destination_selection',x,{databaseCode:error?.code,constraint:error?.constraint});}finally{c.release();}}
 return{start,complete,disconnect,selectDestination,adapter};}
module.exports={createService,outcome,diagnostic,REASONS,hash,sessionFingerprint,requestId,accountId};
