'use strict';
const configModule=require('./linkedin-config');
const {safeError}=require('./errors');
const MAX_BODY=32768, TIMEOUT_MS=8000;
function fail(code,requestId){return {ok:false,error:safeError(code,requestId)};}
async function jsonRequest(url,options,{fetchImpl=globalThis.fetch,timeoutMs=TIMEOUT_MS}={}){
  const controller=new AbortController(),timer=setTimeout(()=>controller.abort(),timeoutMs);
  try{const response=await fetchImpl(url,{...options,signal:controller.signal});const type=response.headers?.get?.('content-type')||'';if(!type.toLowerCase().includes('application/json'))return fail('linkedin_response_invalid');const declared=Number(response.headers?.get?.('content-length'));if(Number.isFinite(declared)&&declared>MAX_BODY)return fail('linkedin_response_invalid');const text=await response.text();if(Buffer.byteLength(text)>MAX_BODY)return fail('linkedin_response_invalid');let body;try{body=JSON.parse(text);}catch{return fail('linkedin_response_invalid');}if(!response.ok)return fail(url===configModule.TOKEN_ENDPOINT?'linkedin_token_exchange_rejected':'linkedin_provider_unavailable');return {ok:true,value:body};}catch{return fail('linkedin_provider_unavailable');}finally{clearTimeout(timer);}
}
function createLinkedInAdapter({env=process.env,fetchImpl=globalThis.fetch}={}){
 const cfg=()=>configModule.load(env);
 return Object.assign(Object.create(null),{capabilities:['getAuthorizationRequest','exchangeAuthorizationCode','discoverAccount','discoverDestinations','getCapabilities','revokeConnection'],
 async getAuthorizationRequest({context,input}){const c=cfg();if(!c.ready)return fail('linkedin_not_configured',context.requestId);const u=new URL(configModule.AUTHORIZATION_ENDPOINT);u.search=new URLSearchParams({response_type:'code',client_id:c.clientId,redirect_uri:c.redirectUri,state:input.state,scope:c.scopes.join(' ')}).toString();return {ok:true,value:{authorizationUrl:u.toString(),requestedScopes:c.scopes,redirectUri:c.redirectUri}};},
 async exchangeAuthorizationCode({context,input}){const c=cfg();if(!c.ready)return fail('linkedin_not_configured',context.requestId);if(typeof input.code!=='string'||input.code.length<2||input.code.length>2048)return fail('linkedin_code_missing',context.requestId);const body=new URLSearchParams({grant_type:'authorization_code',code:input.code,client_id:c.clientId,client_secret:c.clientSecret,redirect_uri:c.redirectUri});const result=await jsonRequest(configModule.TOKEN_ENDPOINT,{method:'POST',headers:{accept:'application/json','content-type':'application/x-www-form-urlencoded','user-agent':'Funklix-Social-Connector/1.0'},body},{fetchImpl});if(!result.ok)return result;const v=result.value;if(typeof v.access_token!=='string'||v.access_token.length<8||v.access_token.length>12000||!Number.isInteger(v.expires_in)||v.expires_in<=0||typeof v.scope!=='string')return fail('linkedin_response_invalid',context.requestId);const grantedScopes=Object.freeze([...new Set(v.scope.split(/\s+/).filter(Boolean))]);const credential={accessToken:v.access_token,tokenType:typeof v.token_type==='string'?v.token_type:'Bearer',scope:grantedScopes.join(' ')};if(typeof v.refresh_token==='string'&&v.refresh_token.length<=12000)credential.refreshToken=v.refresh_token;return {ok:true,value:{credential,grantedScopes,expiresAt:new Date(Date.now()+v.expires_in*1000).toISOString(),refreshExpiresAt:Number.isInteger(v.refresh_token_expires_in)?new Date(Date.now()+v.refresh_token_expires_in*1000).toISOString():null}};},
 async discoverAccount({context,credentials}){if(!credentials||typeof credentials.accessToken!=='string')return fail('linkedin_response_invalid',context.requestId);const result=await jsonRequest(configModule.USERINFO_ENDPOINT,{method:'GET',headers:{accept:'application/json',authorization:`Bearer ${credentials.accessToken}`,'user-agent':'Funklix-Social-Connector/1.0'}},{fetchImpl});if(!result.ok)return result;const v=result.value;if(typeof v.sub!=='string'||!v.sub||v.sub.length>255||typeof v.name!=='string'||!v.name||v.name.length>200)return fail('linkedin_identity_missing',context.requestId);let avatarUrl=null;if(typeof v.picture==='string'&&v.picture.length<=2048){try{const u=new URL(v.picture);if(u.protocol==='https:')avatarUrl=u.toString();}catch{}}return {ok:true,value:{externalAccountId:v.sub,displayName:v.name,avatarUrl,accountType:'personal'}};},
 async discoverDestinations({input}){return {ok:true,value:[{externalDestinationId:input.account.externalAccountId,type:'personal',displayName:input.account.displayName}]};},
 async getCapabilities({input}){const scopes=new Set(input.grantedScopes||[]),healthy=input.health==='connected';return {ok:true,value:{identity:scopes.has('openid')&&scopes.has('profile'),publishingPermission:healthy&&scopes.has('w_member_social'),publishingImplemented:false}};},
 async revokeConnection(){return {ok:true,value:{remoteRevocationSupported:false,localDisconnectRequired:true}};}
 });
}
module.exports={MAX_BODY,TIMEOUT_MS,jsonRequest,createLinkedInAdapter};
