'use strict';
// Server-only. Every statement is intentionally issued separately: deployed pg
// clients need not support a multi-statement query and diagnostics stay bounded.
const {OAUTH_PHASES,sqlLiterals}=require('./oauth-phases');
const SCHEMA_VERSION=4,LOCK_KEY=32320206;
const readyByPool=new WeakMap();
const STEPS=Object.freeze(['transaction_begin','schema_lock_acquire','schema_version_read','read_structure_catalog','read_structure_table','read_structure_column','read_structure_ownership','token_secrets_table','connected_accounts_table','destinations_table','oauth_attempts_table','publish_jobs_table','provider_attempts_table','external_posts_table','oauth_return_path_constraint_inspect','oauth_return_path_constraint_remove','oauth_return_path_normalization','oauth_return_path_constraint_add','oauth_return_path_constraint_validate','oauth_phase_column_inspect','oauth_phase_constraint_inspect','oauth_phase_constraint_remove','oauth_phase_normalization','oauth_phase_constraint_add','oauth_phase_constraint_validate','oauth_connection_association','index_connected_identity','index_token_secrets_owner','index_connected_accounts_owner','index_destinations_owner','index_oauth_owner','index_connected_oauth_attempt','index_publish_jobs_board','index_publish_jobs_due','index_provider_attempts_job','index_external_posts_source','schema_version_write','schema_commit','transaction_rollback','schema_unknown']);
const TABLES=Object.freeze([
 ['token_secrets_table',`CREATE TABLE IF NOT EXISTS public.social_token_secrets (id UUID PRIMARY KEY DEFAULT gen_random_uuid(),owner_account_id TEXT NOT NULL,platform TEXT NOT NULL CHECK(platform IN ('linkedin','instagram','facebook','x')),encrypted_payload TEXT NOT NULL CHECK(octet_length(encrypted_payload)<=32768),nonce TEXT NOT NULL,authentication_tag TEXT NOT NULL,encryption_key_version INTEGER NOT NULL CHECK(encryption_key_version>0),created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),rotated_at TIMESTAMPTZ,revoked_at TIMESTAMPTZ,UNIQUE(id,owner_account_id),UNIQUE(id,owner_account_id,platform))`],
 ['connected_accounts_table',`CREATE TABLE IF NOT EXISTS public.social_connected_accounts (id UUID PRIMARY KEY DEFAULT gen_random_uuid(),owner_account_id TEXT NOT NULL,platform TEXT NOT NULL CHECK(platform IN ('linkedin','instagram','facebook','x')),external_account_id TEXT,external_display_name TEXT,account_type TEXT NOT NULL,status TEXT NOT NULL CHECK(status IN ('pending','connected','needs_attention','revoked','disconnected')),granted_scopes JSONB NOT NULL DEFAULT '[]'::jsonb CHECK(jsonb_typeof(granted_scopes)='array'),token_secret_id UUID,token_expires_at TIMESTAMPTZ,last_validated_at TIMESTAMPTZ,created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),disconnected_at TIMESTAMPTZ,schema_version INTEGER NOT NULL DEFAULT 1 CHECK(schema_version=1),UNIQUE(id,owner_account_id),UNIQUE(id,owner_account_id,platform),FOREIGN KEY(token_secret_id,owner_account_id,platform) REFERENCES public.social_token_secrets(id,owner_account_id,platform) ON DELETE RESTRICT)`],
 ['destinations_table',`CREATE TABLE IF NOT EXISTS public.social_publishing_destinations (id UUID PRIMARY KEY DEFAULT gen_random_uuid(),connected_account_id UUID NOT NULL,owner_account_id TEXT NOT NULL,external_destination_id TEXT NOT NULL,destination_type TEXT NOT NULL,display_name TEXT NOT NULL,capabilities JSONB NOT NULL DEFAULT '[]'::jsonb CHECK(jsonb_typeof(capabilities)='array'),authorization_state TEXT NOT NULL,status TEXT NOT NULL CHECK(status IN ('active','unavailable','unauthorized')),active BOOLEAN NOT NULL DEFAULT TRUE,last_capability_refresh_at TIMESTAMPTZ,created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),UNIQUE(id,owner_account_id),UNIQUE(connected_account_id,external_destination_id),FOREIGN KEY(connected_account_id,owner_account_id) REFERENCES public.social_connected_accounts(id,owner_account_id) ON DELETE RESTRICT)`],
 ['oauth_attempts_table',`CREATE TABLE IF NOT EXISTS public.social_oauth_attempts (id UUID PRIMARY KEY DEFAULT gen_random_uuid(),owner_account_id TEXT NOT NULL,platform TEXT NOT NULL CHECK(platform IN ('linkedin','instagram','facebook','x')),return_path TEXT NOT NULL DEFAULT '/' CHECK(return_path = '/'),state_hash TEXT NOT NULL UNIQUE,pkce_verifier_reference TEXT,session_binding_fingerprint TEXT NOT NULL,failure_classification TEXT,last_confirmed_phase TEXT,client_request_id TEXT,server_request_id TEXT,created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),expires_at TIMESTAMPTZ NOT NULL,consumed_at TIMESTAMPTZ,CHECK(expires_at>created_at))`],
 ['publish_jobs_table',`CREATE TABLE IF NOT EXISTS public.social_publish_jobs (id UUID PRIMARY KEY DEFAULT gen_random_uuid(),owner_account_id TEXT NOT NULL,board_id UUID NOT NULL REFERENCES boards(id) ON DELETE RESTRICT,node_id TEXT NOT NULL,approved_fingerprint TEXT NOT NULL,content_snapshot JSONB NOT NULL CHECK(octet_length(content_snapshot::text)<=65536),destination_id UUID NOT NULL,delivery_mode TEXT NOT NULL CHECK(delivery_mode IN ('immediate','scheduled')),requested_delivery_at TIMESTAMPTZ,original_local_time TEXT,original_timezone TEXT,status TEXT NOT NULL CHECK(status IN ('draft','queued','validating','delivering','delivered','failed','cancelled','outcome_unknown')),idempotency_key TEXT NOT NULL,attempt_count INTEGER NOT NULL DEFAULT 0 CHECK(attempt_count>=0),last_safe_error_classification TEXT,created_by_actor TEXT NOT NULL,created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),cancelled_at TIMESTAMPTZ,completed_at TIMESTAMPTZ,schema_version INTEGER NOT NULL DEFAULT 1 CHECK(schema_version=1),UNIQUE(owner_account_id,idempotency_key),UNIQUE(id,owner_account_id),FOREIGN KEY(destination_id,owner_account_id) REFERENCES public.social_publishing_destinations(id,owner_account_id) ON DELETE RESTRICT)`],
 ['provider_attempts_table',`CREATE TABLE IF NOT EXISTS public.social_provider_attempts (id UUID PRIMARY KEY DEFAULT gen_random_uuid(),publish_job_id UUID NOT NULL,owner_account_id TEXT NOT NULL,adapter_platform TEXT NOT NULL CHECK(adapter_platform IN ('linkedin','instagram','facebook','x')),attempt_number INTEGER NOT NULL CHECK(attempt_number>0),phase TEXT NOT NULL,status TEXT NOT NULL CHECK(status IN ('started','accepted','rejected','temporary_failure','permanent_failure','outcome_unknown','reconciled')),safe_error_classification TEXT,ambiguous_outcome BOOLEAN NOT NULL DEFAULT FALSE,provider_request_reference TEXT,started_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),completed_at TIMESTAMPTZ,UNIQUE(publish_job_id,attempt_number),FOREIGN KEY(publish_job_id,owner_account_id) REFERENCES public.social_publish_jobs(id,owner_account_id) ON DELETE RESTRICT)`],
 ['external_posts_table',`CREATE TABLE IF NOT EXISTS public.social_external_posts (id UUID PRIMARY KEY DEFAULT gen_random_uuid(),platform TEXT NOT NULL CHECK(platform IN ('linkedin','instagram','facebook','x')),external_post_id TEXT NOT NULL,destination_id UUID NOT NULL,publish_job_id UUID NOT NULL,owner_account_id TEXT NOT NULL,source_board_id UUID NOT NULL REFERENCES boards(id) ON DELETE RESTRICT,source_node_id TEXT NOT NULL,approved_fingerprint TEXT NOT NULL,published_snapshot_reference TEXT NOT NULL,external_url TEXT,published_at TIMESTAMPTZ,delivery_state TEXT NOT NULL CHECK(delivery_state IN ('confirmed','outcome_unknown','unavailable','deleted')),deletion_state TEXT NOT NULL CHECK(deletion_state IN ('retained','deleted')),last_synchronized_at TIMESTAMPTZ,schema_version INTEGER NOT NULL DEFAULT 1 CHECK(schema_version=1),UNIQUE(platform,external_post_id),UNIQUE(publish_job_id),FOREIGN KEY(destination_id,owner_account_id) REFERENCES public.social_publishing_destinations(id,owner_account_id) ON DELETE RESTRICT,FOREIGN KEY(publish_job_id,owner_account_id) REFERENCES public.social_publish_jobs(id,owner_account_id) ON DELETE RESTRICT)`]
]);
// The first deployed statement used `CREATE INDEX ... public.name`, which PostgreSQL
// rejects with 42601. Indexes belong to their table's schema; only the table is qualified.
const INDEX_INVENTORY=Object.freeze([
 {category:'index_token_secrets_owner',name:'social_token_secrets_owner_idx',table:'social_token_secrets',columns:'owner_account_id,platform',unique:false,predicate:null,version:1,original:true,correctness:'performance'},
 {category:'index_connected_identity',name:'social_connected_identity_uidx',table:'social_connected_accounts',columns:'owner_account_id,platform,external_account_id',unique:true,predicate:'external_account_id IS NOT NULL',version:1,original:true,correctness:'write'},
 {category:'index_connected_accounts_owner',name:'social_connected_owner_idx',table:'social_connected_accounts',columns:'owner_account_id,status',unique:false,predicate:null,version:1,original:true,correctness:'performance'},
 {category:'index_destinations_owner',name:'social_destinations_owner_idx',table:'social_publishing_destinations',columns:'owner_account_id,status',unique:false,predicate:null,version:1,original:true,correctness:'performance'},
 {category:'index_oauth_owner',name:'social_oauth_owner_idx',table:'social_oauth_attempts',columns:'owner_account_id,created_at DESC',unique:false,predicate:null,version:1,original:true,correctness:'performance'},
 {category:'index_connected_oauth_attempt',name:'social_connected_oauth_attempt_idx',table:'social_connected_accounts',columns:'last_oauth_attempt_id',unique:false,predicate:'last_oauth_attempt_id IS NOT NULL',version:3,original:false,correctness:'performance'},
 {category:'index_publish_jobs_board',name:'social_jobs_board_idx',table:'social_publish_jobs',columns:'board_id,status',unique:false,predicate:null,version:1,original:true,correctness:'performance'},
 {category:'index_publish_jobs_due',name:'social_jobs_delivery_idx',table:'social_publish_jobs',columns:'status,requested_delivery_at',unique:false,predicate:null,version:1,original:true,correctness:'performance'},
 {category:'index_provider_attempts_job',name:'social_attempts_job_idx',table:'social_provider_attempts',columns:'publish_job_id,started_at DESC',unique:false,predicate:null,version:1,original:true,correctness:'performance'},
 {category:'index_external_posts_source',name:'social_external_source_idx',table:'social_external_posts',columns:'owner_account_id,source_board_id,source_node_id',unique:false,predicate:null,version:1,original:true,correctness:'performance'}
].map(x=>Object.freeze({...x,schema:'public',equivalentMayExist:true,blocksReads:false,blocksWrites:x.correctness==='write'})));
function indexSql(index){return `CREATE ${index.unique?'UNIQUE ':''}INDEX IF NOT EXISTS ${index.name} ON public.${index.table}(${index.columns})${index.predicate?` WHERE ${index.predicate}`:''}`;}
const REQUIRED_INDEXES=INDEX_INVENTORY.filter(x=>x.correctness==='write');
const OPTIONAL_INDEXES=INDEX_INVENTORY.filter(x=>x.correctness==='performance');
const INDEXES=INDEX_INVENTORY.map(indexSql);
// Inspection-only compatibility export; execution never sends this as one query.
const SCHEMA_SQL=[...TABLES.map(([,sql])=>sql),...INDEXES].join(';\n');
function databaseErrorCategory(code='') {if(code==='42601')return'syntax_error';if(code==='42501')return'insufficient_privilege';if(code==='42710'||code==='42P07')return'duplicate_object';if(code==='42703')return'undefined_column';if(code==='42P01')return'undefined_table';if(code==='42830')return'invalid_foreign_key';if(code==='23514')return'check_violation';if(code==='23505')return'unique_violation';if(code==='2BP01')return'dependent_objects';if(code==='25P02')return'transaction_aborted';if(code.startsWith('55')||code==='40P01')return'lock_failure';if(code.startsWith('08'))return'connection_failure';return'unknown_database_error';}
function mark(diagnostic,step){if(diagnostic)Object.assign(diagnostic,{phase:'schema_initialization',operation_category:STEPS.includes(step)?step:'schema_unknown'});}
async function run(client,diagnostic,step,sql,params){mark(diagnostic,step);return client.query(sql,params);}
function canonicalReturnPath(definition=''){return /return_path\s*=\s*'\/'(?:::text)?/i.test(definition);}
function canonicalPhase(definition=''){const values=[...definition.matchAll(/'([^']+)'/g)].map(match=>match[1]);return values.length===OAUTH_PHASES.length&&values.every(value=>OAUTH_PHASES.includes(value));}
async function migrate(pool,diagnostic){const client=typeof pool.connect==='function'?await pool.connect():pool;let begun=false,version=0;try{
 await run(client,diagnostic,'transaction_begin','BEGIN');begun=true;
 await run(client,diagnostic,'schema_lock_acquire','SELECT pg_advisory_xact_lock($1)',[LOCK_KEY]);
 await run(client,diagnostic,'schema_version_read',`CREATE TABLE IF NOT EXISTS public.social_connector_schema_version (singleton BOOLEAN PRIMARY KEY DEFAULT TRUE CHECK(singleton),version INTEGER NOT NULL CHECK(version>=0),updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW())`);
 const found=await run(client,diagnostic,'schema_version_read','SELECT version FROM public.social_connector_schema_version WHERE singleton=TRUE');version=Number(found.rows[0]?.version||0);if(diagnostic)diagnostic.schema_committed_version=version;
 if(version<1)for(const [step,sql] of TABLES)await run(client,diagnostic,step,sql);
 if(version<2){await run(client,diagnostic,'oauth_phase_column_inspect',`ALTER TABLE public.social_oauth_attempts ADD COLUMN IF NOT EXISTS last_confirmed_phase TEXT`);await run(client,diagnostic,'oauth_phase_column_inspect',`ALTER TABLE public.social_oauth_attempts ADD COLUMN IF NOT EXISTS client_request_id TEXT`);await run(client,diagnostic,'oauth_phase_column_inspect',`ALTER TABLE public.social_oauth_attempts ADD COLUMN IF NOT EXISTS server_request_id TEXT`);}
 if(version<3){await run(client,diagnostic,'oauth_connection_association',`ALTER TABLE public.social_connected_accounts ADD COLUMN IF NOT EXISTS last_oauth_attempt_id UUID`);const fk=await run(client,diagnostic,'oauth_connection_association',`SELECT 1 FROM pg_constraint WHERE conrelid='public.social_connected_accounts'::regclass AND conname='social_connected_accounts_oauth_attempt_fk'`);if(!fk.rows[0])await run(client,diagnostic,'oauth_connection_association',`ALTER TABLE public.social_connected_accounts ADD CONSTRAINT social_connected_accounts_oauth_attempt_fk FOREIGN KEY(last_oauth_attempt_id) REFERENCES public.social_oauth_attempts(id) ON DELETE SET NULL`);}
 if(version<SCHEMA_VERSION){
  const column=await run(client,diagnostic,'oauth_phase_column_inspect',`SELECT 1 FROM information_schema.columns WHERE table_schema='public' AND table_name='social_oauth_attempts' AND column_name='last_confirmed_phase'`);if(!column.rows[0])await run(client,diagnostic,'oauth_phase_column_inspect',`ALTER TABLE public.social_oauth_attempts ADD COLUMN last_confirmed_phase TEXT`);
  const rp=await run(client,diagnostic,'oauth_return_path_constraint_inspect',`SELECT pg_get_constraintdef(oid) definition,convalidated FROM pg_constraint WHERE conrelid='public.social_oauth_attempts'::regclass AND conname='social_oauth_attempts_return_path_check'`);const rpOk=!!rp.rows[0]&&rp.rows[0].convalidated===true&&canonicalReturnPath(rp.rows[0].definition);if(!rpOk){if(rp.rows[0])await run(client,diagnostic,'oauth_return_path_constraint_remove',`ALTER TABLE public.social_oauth_attempts DROP CONSTRAINT social_oauth_attempts_return_path_check`);await run(client,diagnostic,'oauth_return_path_normalization',`UPDATE public.social_oauth_attempts SET return_path='/' WHERE return_path IS DISTINCT FROM '/'`);await run(client,diagnostic,'oauth_return_path_constraint_add',`ALTER TABLE public.social_oauth_attempts ALTER COLUMN return_path SET DEFAULT '/',ALTER COLUMN return_path SET NOT NULL,ADD CONSTRAINT social_oauth_attempts_return_path_check CHECK(return_path = '/') NOT VALID`);await run(client,diagnostic,'oauth_return_path_constraint_validate',`ALTER TABLE public.social_oauth_attempts VALIDATE CONSTRAINT social_oauth_attempts_return_path_check`);}
  const pc=await run(client,diagnostic,'oauth_phase_constraint_inspect',`SELECT pg_get_constraintdef(oid) definition,convalidated FROM pg_constraint WHERE conrelid='public.social_oauth_attempts'::regclass AND conname='social_oauth_attempts_last_confirmed_phase_check'`);const pcOk=!!pc.rows[0]&&pc.rows[0].convalidated===true&&canonicalPhase(pc.rows[0].definition);if(!pcOk){if(pc.rows[0])await run(client,diagnostic,'oauth_phase_constraint_remove',`ALTER TABLE public.social_oauth_attempts DROP CONSTRAINT social_oauth_attempts_last_confirmed_phase_check`);await run(client,diagnostic,'oauth_phase_normalization',`UPDATE public.social_oauth_attempts SET last_confirmed_phase='unknown' WHERE last_confirmed_phase IS NOT NULL AND NOT (last_confirmed_phase = ANY($1::text[]))`,[OAUTH_PHASES]);await run(client,diagnostic,'oauth_phase_constraint_add',`ALTER TABLE public.social_oauth_attempts ADD CONSTRAINT social_oauth_attempts_last_confirmed_phase_check CHECK(last_confirmed_phase IS NULL OR last_confirmed_phase IN (${sqlLiterals()})) NOT VALID`);await run(client,diagnostic,'oauth_phase_constraint_validate',`ALTER TABLE public.social_oauth_attempts VALIDATE CONSTRAINT social_oauth_attempts_last_confirmed_phase_check`);}
  // Only the external-account identity invariant is correctness-critical. Lookup
  // indexes are repaired explicitly and never share this transaction/read path.
  for(const index of REQUIRED_INDEXES)await run(client,diagnostic,index.category,indexSql(index));
  await run(client,diagnostic,'schema_version_write',`INSERT INTO public.social_connector_schema_version(singleton,version) VALUES(TRUE,$1) ON CONFLICT(singleton) DO UPDATE SET version=EXCLUDED.version,updated_at=NOW()`,[SCHEMA_VERSION]);
 }
 await run(client,diagnostic,'schema_commit','COMMIT');begun=false;if(diagnostic)Object.assign(diagnostic,{schema_target_version:SCHEMA_VERSION,schema_committed_version:version<SCHEMA_VERSION?SCHEMA_VERSION:version});return {version:version<SCHEMA_VERSION?SCHEMA_VERSION:version,targetVersion:SCHEMA_VERSION,changed:version<SCHEMA_VERSION};
 }catch(error){const failedStep=diagnostic&&diagnostic.operation_category,category=databaseErrorCategory(error&&error.code);if(begun){try{await run(client,diagnostic,'transaction_rollback','ROLLBACK');}catch{}}if(diagnostic)Object.assign(diagnostic,{phase:'schema_initialization',operation_category:failedStep||'schema_unknown',database_error_category:category,schema_target_version:SCHEMA_VERSION,schema_committed_version:version});throw error;}finally{if(client!==pool&&typeof client.release==='function')client.release();}}
async function ensureSocialConnectorSchema(poolOverride,diagnostic){const pool=poolOverride||require('../_boards-storage').pool;if(!readyByPool.has(pool)){const pending=migrate(pool,diagnostic).catch(error=>{readyByPool.delete(pool);throw error;});readyByPool.set(pool,pending);}return readyByPool.get(pool);}
const READ_TABLES=Object.freeze({
 social_token_secrets:['id','owner_account_id','platform','revoked_at','encryption_key_version'],
 social_connected_accounts:['id','owner_account_id','platform','external_display_name','account_type','status','granted_scopes','token_secret_id','token_expires_at','last_oauth_attempt_id','created_at','updated_at','disconnected_at','schema_version'],
 social_publishing_destinations:['id','connected_account_id','owner_account_id','status','active','created_at']
});
async function readCompatibilityPreflight(pool,diagnostic={}){let version=0;try{
 mark(diagnostic,'read_structure_catalog');
 const columns=await pool.query(`SELECT table_name,column_name,data_type FROM information_schema.columns WHERE table_schema='public' AND table_name = ANY($1::text[])`,[Object.keys(READ_TABLES)]);
 const present=new Map();for(const row of columns.rows||[]){if(!present.has(row.table_name))present.set(row.table_name,new Set());present.get(row.table_name).add(row.column_name);}
 const missingTables=Object.keys(READ_TABLES).filter(table=>!present.has(table));
 if(missingTables.length)return {status:'migration_required',structuralState:'migration_required',maintenanceState:'unknown',committedVersion:0,missingTables};
 const missingColumns=[];for(const [table,names] of Object.entries(READ_TABLES))for(const name of names)if(!present.get(table).has(name))missingColumns.push(`${table}.${name}`);
 if(missingColumns.length){mark(diagnostic,'read_structure_column');return {status:'structurally_inconsistent',structuralState:'inconsistent',maintenanceState:'unknown',committedVersion:0,missingColumns};}
 mark(diagnostic,'read_structure_ownership');
 const constraints=await pool.query(`SELECT conrelid::regclass::text AS table_name,contype,pg_get_constraintdef(oid) AS definition FROM pg_constraint WHERE conrelid IN ('public.social_token_secrets'::regclass,'public.social_connected_accounts'::regclass,'public.social_publishing_destinations'::regclass)`);
 const definitions=(constraints.rows||[]).map(x=>`${x.table_name} ${x.contype} ${x.definition}`);
 const ownershipOk=['social_token_secrets','social_connected_accounts','social_publishing_destinations'].every(table=>definitions.some(x=>new RegExp(`${table}.*PRIMARY KEY`,'i').test(x)))&&definitions.some(x=>/social_connected_accounts.*FOREIGN KEY.*token_secret_id.*owner_account_id.*platform/i.test(x))&&definitions.some(x=>/social_publishing_destinations.*FOREIGN KEY.*connected_account_id.*owner_account_id/i.test(x));
 if(!ownershipOk)return {status:'structurally_inconsistent',structuralState:'inconsistent',maintenanceState:'unknown',committedVersion:0,reason:'required_ownership_constraint'};
 try{const versionTable=await pool.query(`SELECT to_regclass('public.social_connector_schema_version') AS relation`);if(versionTable.rows?.[0]?.relation){const result=await pool.query('SELECT version FROM public.social_connector_schema_version WHERE singleton=TRUE');version=Number(result.rows?.[0]?.version||0);}}catch{version=0;}
 let maintenanceState='unknown';try{const existing=await pool.query(`SELECT indexname FROM pg_indexes WHERE schemaname='public' AND indexname = ANY($1::text[])`,[OPTIONAL_INDEXES.map(x=>x.name)]);maintenanceState=(existing.rows||[]).length===OPTIONAL_INDEXES.length?'current':'indexes_pending';}catch{}
 Object.assign(diagnostic,{schema_committed_version:version,schema_structural_state:version>=SCHEMA_VERSION?'current':'compatible_existing',schema_maintenance_state:maintenanceState});
 return {status:'read_compatible',structuralState:diagnostic.schema_structural_state,maintenanceState,committedVersion:version};
 }catch(error){Object.assign(diagnostic,{database_error_category:databaseErrorCategory(error?.code),schema_committed_version:version,schema_structural_state:'inconsistent',schema_maintenance_state:'unknown'});return {status:'storage_unavailable',structuralState:'inconsistent',maintenanceState:'unknown',committedVersion:version,error};}}
async function migrateRequiredReadStructure(pool,preflight,diagnostic){const missing=new Set(preflight.missingTables||[]);for(const [step,sql] of TABLES.slice(0,3))if(missing.has(sql.match(/public\.(social_[a-z_]+)/)?.[1]))await run(pool,diagnostic,step,sql);return readCompatibilityPreflight(pool,diagnostic);}
async function maintainOptionalIndexes(pool,diagnostic={}){for(const index of OPTIONAL_INDEXES){try{mark(diagnostic,index.category);const found=await pool.query(`SELECT indexname,pg_get_indexdef(indexrelid) AS definition FROM pg_indexes JOIN pg_class ON relname=indexname WHERE schemaname='public' AND tablename=$1`,[index.table]);const signature=index.columns.replace(/\s+/g,'').toLowerCase();if((found.rows||[]).some(row=>String(row.definition).replace(/\s+/g,'').toLowerCase().includes(`(${signature})`)))continue;await pool.query(indexSql(index));}catch(error){Object.assign(diagnostic,{database_error_category:databaseErrorCategory(error?.code),schema_maintenance_state:'maintenance_failed'});return {state:'maintenance_failed',failedCategory:index.category};}}return {state:'current'};}
module.exports={SCHEMA_VERSION,STEPS,TABLES,INDEXES,INDEX_INVENTORY,REQUIRED_INDEXES,OPTIONAL_INDEXES,READ_TABLES,SCHEMA_SQL,canonicalReturnPath,canonicalPhase,databaseErrorCategory,migrate,ensureSocialConnectorSchema,readCompatibilityPreflight,migrateRequiredReadStructure,maintainOptionalIndexes};
