'use strict';
// Server-only. Every statement is intentionally issued separately: deployed pg
// clients need not support a multi-statement query and diagnostics stay bounded.
const {OAUTH_PHASES,sqlLiterals}=require('./oauth-phases');
const SCHEMA_VERSION=4,LOCK_KEY=32320206;
const readyByPool=new WeakMap();
const STEPS=Object.freeze(['transaction_begin','schema_lock_acquire','schema_version_read','token_secrets_table','connected_accounts_table','destinations_table','oauth_attempts_table','publish_jobs_table','provider_attempts_table','external_posts_table','oauth_return_path_constraint_inspect','oauth_return_path_constraint_remove','oauth_return_path_normalization','oauth_return_path_constraint_add','oauth_return_path_constraint_validate','oauth_phase_column_inspect','oauth_phase_constraint_inspect','oauth_phase_constraint_remove','oauth_phase_normalization','oauth_phase_constraint_add','oauth_phase_constraint_validate','oauth_connection_association','schema_indexes','schema_version_write','schema_commit','transaction_rollback','schema_unknown']);
const TABLES=Object.freeze([
 ['token_secrets_table',`CREATE TABLE IF NOT EXISTS public.social_token_secrets (id UUID PRIMARY KEY DEFAULT gen_random_uuid(),owner_account_id TEXT NOT NULL,platform TEXT NOT NULL CHECK(platform IN ('linkedin','instagram','facebook','x')),encrypted_payload TEXT NOT NULL CHECK(octet_length(encrypted_payload)<=32768),nonce TEXT NOT NULL,authentication_tag TEXT NOT NULL,encryption_key_version INTEGER NOT NULL CHECK(encryption_key_version>0),created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),rotated_at TIMESTAMPTZ,revoked_at TIMESTAMPTZ,UNIQUE(id,owner_account_id),UNIQUE(id,owner_account_id,platform))`],
 ['connected_accounts_table',`CREATE TABLE IF NOT EXISTS public.social_connected_accounts (id UUID PRIMARY KEY DEFAULT gen_random_uuid(),owner_account_id TEXT NOT NULL,platform TEXT NOT NULL CHECK(platform IN ('linkedin','instagram','facebook','x')),external_account_id TEXT,external_display_name TEXT,account_type TEXT NOT NULL,status TEXT NOT NULL CHECK(status IN ('pending','connected','needs_attention','revoked','disconnected')),granted_scopes JSONB NOT NULL DEFAULT '[]'::jsonb CHECK(jsonb_typeof(granted_scopes)='array'),token_secret_id UUID,token_expires_at TIMESTAMPTZ,last_validated_at TIMESTAMPTZ,created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),disconnected_at TIMESTAMPTZ,schema_version INTEGER NOT NULL DEFAULT 1 CHECK(schema_version=1),UNIQUE(id,owner_account_id),UNIQUE(id,owner_account_id,platform),FOREIGN KEY(token_secret_id,owner_account_id,platform) REFERENCES public.social_token_secrets(id,owner_account_id,platform) ON DELETE RESTRICT)`],
 ['destinations_table',`CREATE TABLE IF NOT EXISTS public.social_publishing_destinations (id UUID PRIMARY KEY DEFAULT gen_random_uuid(),connected_account_id UUID NOT NULL,owner_account_id TEXT NOT NULL,external_destination_id TEXT NOT NULL,destination_type TEXT NOT NULL,display_name TEXT NOT NULL,capabilities JSONB NOT NULL DEFAULT '[]'::jsonb CHECK(jsonb_typeof(capabilities)='array'),authorization_state TEXT NOT NULL,status TEXT NOT NULL CHECK(status IN ('active','unavailable','unauthorized')),active BOOLEAN NOT NULL DEFAULT TRUE,last_capability_refresh_at TIMESTAMPTZ,created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),UNIQUE(id,owner_account_id),UNIQUE(connected_account_id,external_destination_id),FOREIGN KEY(connected_account_id,owner_account_id) REFERENCES public.social_connected_accounts(id,owner_account_id) ON DELETE RESTRICT)`],
 ['oauth_attempts_table',`CREATE TABLE IF NOT EXISTS public.social_oauth_attempts (id UUID PRIMARY KEY DEFAULT gen_random_uuid(),owner_account_id TEXT NOT NULL,platform TEXT NOT NULL CHECK(platform IN ('linkedin','instagram','facebook','x')),return_path TEXT NOT NULL DEFAULT '/' CHECK(return_path = '/'),state_hash TEXT NOT NULL UNIQUE,pkce_verifier_reference TEXT,session_binding_fingerprint TEXT NOT NULL,failure_classification TEXT,last_confirmed_phase TEXT,client_request_id TEXT,server_request_id TEXT,created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),expires_at TIMESTAMPTZ NOT NULL,consumed_at TIMESTAMPTZ,CHECK(expires_at>created_at))`],
 ['publish_jobs_table',`CREATE TABLE IF NOT EXISTS public.social_publish_jobs (id UUID PRIMARY KEY DEFAULT gen_random_uuid(),owner_account_id TEXT NOT NULL,board_id UUID NOT NULL REFERENCES boards(id) ON DELETE RESTRICT,node_id TEXT NOT NULL,approved_fingerprint TEXT NOT NULL,content_snapshot JSONB NOT NULL CHECK(octet_length(content_snapshot::text)<=65536),destination_id UUID NOT NULL,delivery_mode TEXT NOT NULL CHECK(delivery_mode IN ('immediate','scheduled')),requested_delivery_at TIMESTAMPTZ,original_local_time TEXT,original_timezone TEXT,status TEXT NOT NULL CHECK(status IN ('draft','queued','validating','delivering','delivered','failed','cancelled','outcome_unknown')),idempotency_key TEXT NOT NULL,attempt_count INTEGER NOT NULL DEFAULT 0 CHECK(attempt_count>=0),last_safe_error_classification TEXT,created_by_actor TEXT NOT NULL,created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),cancelled_at TIMESTAMPTZ,completed_at TIMESTAMPTZ,schema_version INTEGER NOT NULL DEFAULT 1 CHECK(schema_version=1),UNIQUE(owner_account_id,idempotency_key),UNIQUE(id,owner_account_id),FOREIGN KEY(destination_id,owner_account_id) REFERENCES public.social_publishing_destinations(id,owner_account_id) ON DELETE RESTRICT)`],
 ['provider_attempts_table',`CREATE TABLE IF NOT EXISTS public.social_provider_attempts (id UUID PRIMARY KEY DEFAULT gen_random_uuid(),publish_job_id UUID NOT NULL,owner_account_id TEXT NOT NULL,adapter_platform TEXT NOT NULL CHECK(adapter_platform IN ('linkedin','instagram','facebook','x')),attempt_number INTEGER NOT NULL CHECK(attempt_number>0),phase TEXT NOT NULL,status TEXT NOT NULL CHECK(status IN ('started','accepted','rejected','temporary_failure','permanent_failure','outcome_unknown','reconciled')),safe_error_classification TEXT,ambiguous_outcome BOOLEAN NOT NULL DEFAULT FALSE,provider_request_reference TEXT,started_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),completed_at TIMESTAMPTZ,UNIQUE(publish_job_id,attempt_number),FOREIGN KEY(publish_job_id,owner_account_id) REFERENCES public.social_publish_jobs(id,owner_account_id) ON DELETE RESTRICT)`],
 ['external_posts_table',`CREATE TABLE IF NOT EXISTS public.social_external_posts (id UUID PRIMARY KEY DEFAULT gen_random_uuid(),platform TEXT NOT NULL CHECK(platform IN ('linkedin','instagram','facebook','x')),external_post_id TEXT NOT NULL,destination_id UUID NOT NULL,publish_job_id UUID NOT NULL,owner_account_id TEXT NOT NULL,source_board_id UUID NOT NULL REFERENCES boards(id) ON DELETE RESTRICT,source_node_id TEXT NOT NULL,approved_fingerprint TEXT NOT NULL,published_snapshot_reference TEXT NOT NULL,external_url TEXT,published_at TIMESTAMPTZ,delivery_state TEXT NOT NULL CHECK(delivery_state IN ('confirmed','outcome_unknown','unavailable','deleted')),deletion_state TEXT NOT NULL CHECK(deletion_state IN ('retained','deleted')),last_synchronized_at TIMESTAMPTZ,schema_version INTEGER NOT NULL DEFAULT 1 CHECK(schema_version=1),UNIQUE(platform,external_post_id),UNIQUE(publish_job_id),FOREIGN KEY(destination_id,owner_account_id) REFERENCES public.social_publishing_destinations(id,owner_account_id) ON DELETE RESTRICT,FOREIGN KEY(publish_job_id,owner_account_id) REFERENCES public.social_publish_jobs(id,owner_account_id) ON DELETE RESTRICT)`]
]);
const INDEXES=[`CREATE INDEX IF NOT EXISTS public.social_token_secrets_owner_idx ON public.social_token_secrets(owner_account_id,platform)`,`CREATE UNIQUE INDEX IF NOT EXISTS social_connected_identity_uidx ON public.social_connected_accounts(owner_account_id,platform,external_account_id) WHERE external_account_id IS NOT NULL`,`CREATE INDEX IF NOT EXISTS social_connected_owner_idx ON public.social_connected_accounts(owner_account_id,status)`,`CREATE INDEX IF NOT EXISTS social_destinations_owner_idx ON public.social_publishing_destinations(owner_account_id,status)`,`CREATE INDEX IF NOT EXISTS social_oauth_owner_idx ON public.social_oauth_attempts(owner_account_id,created_at DESC)`,`CREATE INDEX IF NOT EXISTS social_connected_oauth_attempt_idx ON public.social_connected_accounts(last_oauth_attempt_id) WHERE last_oauth_attempt_id IS NOT NULL`,`CREATE INDEX IF NOT EXISTS social_jobs_board_idx ON public.social_publish_jobs(board_id,status)`,`CREATE INDEX IF NOT EXISTS social_jobs_delivery_idx ON public.social_publish_jobs(status,requested_delivery_at)`,`CREATE INDEX IF NOT EXISTS social_attempts_job_idx ON public.social_provider_attempts(publish_job_id,started_at DESC)`,`CREATE INDEX IF NOT EXISTS social_external_source_idx ON public.social_external_posts(owner_account_id,source_board_id,source_node_id)`];
// Inspection-only compatibility export; execution never sends this as one query.
const SCHEMA_SQL=[...TABLES.map(([,sql])=>sql),...INDEXES].join(';\n');
function databaseErrorCategory(code='') {if(code==='42501')return'insufficient_privilege';if(code==='42710'||code==='42P07')return'duplicate_object';if(code==='42703')return'undefined_column';if(code==='42P01')return'undefined_table';if(code==='42830')return'invalid_foreign_key';if(code==='23514')return'check_violation';if(code==='23505')return'unique_violation';if(code==='2BP01')return'dependent_objects';if(code==='25P02')return'transaction_aborted';if(code.startsWith('55')||code==='40P01')return'lock_failure';if(code.startsWith('08'))return'connection_failure';return'unknown_database_error';}
function mark(diagnostic,step){if(diagnostic)Object.assign(diagnostic,{phase:'schema_initialization',operation_category:STEPS.includes(step)?step:'schema_unknown'});}
async function run(client,diagnostic,step,sql,params){mark(diagnostic,step);return client.query(sql,params);}
function canonicalReturnPath(definition=''){return /return_path\s*=\s*'\/'(?:::text)?/i.test(definition);}
function canonicalPhase(definition=''){const values=[...definition.matchAll(/'([^']+)'/g)].map(match=>match[1]);return values.length===OAUTH_PHASES.length&&values.every(value=>OAUTH_PHASES.includes(value));}
async function migrate(pool,diagnostic){const client=typeof pool.connect==='function'?await pool.connect():pool;let begun=false,version=0;try{
 await run(client,diagnostic,'transaction_begin','BEGIN');begun=true;
 await run(client,diagnostic,'schema_lock_acquire','SELECT pg_advisory_xact_lock($1)',[LOCK_KEY]);
 await run(client,diagnostic,'schema_version_read',`CREATE TABLE IF NOT EXISTS public.social_connector_schema_version (singleton BOOLEAN PRIMARY KEY DEFAULT TRUE CHECK(singleton),version INTEGER NOT NULL CHECK(version>=0),updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW())`);
 const found=await run(client,diagnostic,'schema_version_read','SELECT version FROM public.social_connector_schema_version WHERE singleton=TRUE');version=Number(found.rows[0]?.version||0);if(diagnostic)diagnostic.schema_committed_version=version;
 if(version<1)for(const [step,sql] of TABLES)await run(client,diagnostic,step,sql);
 if(version<2){await run(client,diagnostic,'oauth_phase_column_inspect',`ALTER TABLE public.social_oauth_attempts ADD COLUMN IF NOT EXISTS last_confirmed_phase TEXT`);await run(client,diagnostic,'oauth_phase_column_inspect',`ALTER TABLE public.social_oauth_attempts ADD COLUMN IF NOT EXISTS client_request_id TEXT`);await run(client,diagnostic,'oauth_phase_column_inspect',`ALTER TABLE public.social_oauth_attempts ADD COLUMN IF NOT EXISTS server_request_id TEXT`);}
 if(version<3){await run(client,diagnostic,'oauth_connection_association',`ALTER TABLE public.social_connected_accounts ADD COLUMN IF NOT EXISTS last_oauth_attempt_id UUID`);const fk=await run(client,diagnostic,'oauth_connection_association',`SELECT 1 FROM pg_constraint WHERE conrelid='public.social_connected_accounts'::regclass AND conname='social_connected_accounts_oauth_attempt_fk'`);if(!fk.rows[0])await run(client,diagnostic,'oauth_connection_association',`ALTER TABLE public.social_connected_accounts ADD CONSTRAINT social_connected_accounts_oauth_attempt_fk FOREIGN KEY(last_oauth_attempt_id) REFERENCES public.social_oauth_attempts(id) ON DELETE SET NULL`);}
 if(version<SCHEMA_VERSION){
  const column=await run(client,diagnostic,'oauth_phase_column_inspect',`SELECT 1 FROM information_schema.columns WHERE table_schema='public' AND table_name='social_oauth_attempts' AND column_name='last_confirmed_phase'`);if(!column.rows[0])await run(client,diagnostic,'oauth_phase_column_inspect',`ALTER TABLE public.social_oauth_attempts ADD COLUMN last_confirmed_phase TEXT`);
  const rp=await run(client,diagnostic,'oauth_return_path_constraint_inspect',`SELECT pg_get_constraintdef(oid) definition,convalidated FROM pg_constraint WHERE conrelid='public.social_oauth_attempts'::regclass AND conname='social_oauth_attempts_return_path_check'`);const rpOk=!!rp.rows[0]&&rp.rows[0].convalidated===true&&canonicalReturnPath(rp.rows[0].definition);if(!rpOk){if(rp.rows[0])await run(client,diagnostic,'oauth_return_path_constraint_remove',`ALTER TABLE public.social_oauth_attempts DROP CONSTRAINT social_oauth_attempts_return_path_check`);await run(client,diagnostic,'oauth_return_path_normalization',`UPDATE public.social_oauth_attempts SET return_path='/' WHERE return_path IS DISTINCT FROM '/'`);await run(client,diagnostic,'oauth_return_path_constraint_add',`ALTER TABLE public.social_oauth_attempts ALTER COLUMN return_path SET DEFAULT '/',ALTER COLUMN return_path SET NOT NULL,ADD CONSTRAINT social_oauth_attempts_return_path_check CHECK(return_path = '/') NOT VALID`);await run(client,diagnostic,'oauth_return_path_constraint_validate',`ALTER TABLE public.social_oauth_attempts VALIDATE CONSTRAINT social_oauth_attempts_return_path_check`);}
  const pc=await run(client,diagnostic,'oauth_phase_constraint_inspect',`SELECT pg_get_constraintdef(oid) definition,convalidated FROM pg_constraint WHERE conrelid='public.social_oauth_attempts'::regclass AND conname='social_oauth_attempts_last_confirmed_phase_check'`);const pcOk=!!pc.rows[0]&&pc.rows[0].convalidated===true&&canonicalPhase(pc.rows[0].definition);if(!pcOk){if(pc.rows[0])await run(client,diagnostic,'oauth_phase_constraint_remove',`ALTER TABLE public.social_oauth_attempts DROP CONSTRAINT social_oauth_attempts_last_confirmed_phase_check`);await run(client,diagnostic,'oauth_phase_normalization',`UPDATE public.social_oauth_attempts SET last_confirmed_phase='unknown' WHERE last_confirmed_phase IS NOT NULL AND NOT (last_confirmed_phase = ANY($1::text[]))`,[OAUTH_PHASES]);await run(client,diagnostic,'oauth_phase_constraint_add',`ALTER TABLE public.social_oauth_attempts ADD CONSTRAINT social_oauth_attempts_last_confirmed_phase_check CHECK(last_confirmed_phase IS NULL OR last_confirmed_phase IN (${sqlLiterals()})) NOT VALID`);await run(client,diagnostic,'oauth_phase_constraint_validate',`ALTER TABLE public.social_oauth_attempts VALIDATE CONSTRAINT social_oauth_attempts_last_confirmed_phase_check`);}
  for(const sql of INDEXES)await run(client,diagnostic,'schema_indexes',sql);
  await run(client,diagnostic,'schema_version_write',`INSERT INTO public.social_connector_schema_version(singleton,version) VALUES(TRUE,$1) ON CONFLICT(singleton) DO UPDATE SET version=EXCLUDED.version,updated_at=NOW()`,[SCHEMA_VERSION]);
 }
 await run(client,diagnostic,'schema_commit','COMMIT');begun=false;if(diagnostic)Object.assign(diagnostic,{schema_target_version:SCHEMA_VERSION,schema_committed_version:version<SCHEMA_VERSION?SCHEMA_VERSION:version});return {version:version<SCHEMA_VERSION?SCHEMA_VERSION:version,targetVersion:SCHEMA_VERSION,changed:version<SCHEMA_VERSION};
 }catch(error){const failedStep=diagnostic&&diagnostic.operation_category,category=databaseErrorCategory(error&&error.code);if(begun){try{await run(client,diagnostic,'transaction_rollback','ROLLBACK');}catch{}}if(diagnostic)Object.assign(diagnostic,{phase:'schema_initialization',operation_category:failedStep||'schema_unknown',database_error_category:category,schema_target_version:SCHEMA_VERSION,schema_committed_version:version});throw error;}finally{if(client!==pool&&typeof client.release==='function')client.release();}}
async function ensureSocialConnectorSchema(poolOverride,diagnostic){const pool=poolOverride||require('../_boards-storage').pool;if(!readyByPool.has(pool)){const pending=migrate(pool,diagnostic).catch(error=>{readyByPool.delete(pool);throw error;});readyByPool.set(pool,pending);}return readyByPool.get(pool);}
module.exports={SCHEMA_VERSION,STEPS,TABLES,INDEXES,SCHEMA_SQL,canonicalReturnPath,canonicalPhase,databaseErrorCategory,migrate,ensureSocialConnectorSchema};
