-- BW-36.7R3 corrected Workspace backfill preflight.
-- Manually run this single read-only, aggregate-only statement in the authenticated Supabase SQL Editor.
WITH
schema_checks AS (
  SELECT * FROM (VALUES
    ('app_identities_table', to_regclass('public.app_identities') IS NOT NULL),
    ('stable_uuid_primary_key', EXISTS (SELECT 1 FROM information_schema.columns c JOIN pg_constraint k ON k.conrelid='public.app_identities'::regclass AND k.contype='p' WHERE c.table_schema='public' AND c.table_name='app_identities' AND c.column_name='id' AND c.data_type='uuid' AND c.column_name=ANY(SELECT a.attname FROM pg_attribute a WHERE a.attrelid=k.conrelid AND a.attnum=ANY(k.conkey)))),
    ('canonical_email_column', EXISTS (SELECT 1 FROM information_schema.columns WHERE table_schema='public' AND table_name='app_identities' AND column_name='canonical_email' AND data_type='text' AND is_nullable='NO')),
    ('canonical_email_normalization_constraint', EXISTS (SELECT 1 FROM pg_constraint WHERE conrelid='public.app_identities'::regclass AND conname='app_identities_canonical_email_check' AND pg_get_constraintdef(oid) LIKE '%lower(btrim(canonical_email))%')),
    ('unique_canonical_email_index', EXISTS (SELECT 1 FROM pg_indexes WHERE schemaname='public' AND tablename='app_identities' AND indexname='app_identities_canonical_email_key' AND indexdef LIKE 'CREATE UNIQUE INDEX%')),
    ('exact_identity_status_constraint', EXISTS (SELECT 1 FROM pg_constraint WHERE conrelid='public.app_identities'::regclass AND conname='app_identities_status_check' AND pg_get_constraintdef(oid) LIKE '%active%' AND pg_get_constraintdef(oid) LIKE '%disabled%')),
    ('non_negative_identity_revision', EXISTS (SELECT 1 FROM pg_constraint WHERE conrelid='public.app_identities'::regclass AND conname='app_identities_revision_check' AND pg_get_constraintdef(oid) LIKE '%revision >= 0%')),
    ('identity_timestamps', (SELECT count(*)=2 FROM information_schema.columns WHERE table_schema='public' AND table_name='app_identities' AND column_name IN ('created_at','updated_at') AND data_type='timestamp with time zone' AND is_nullable='NO')),
    ('identity_rls_enabled', coalesce((SELECT relrowsecurity FROM pg_class WHERE oid='public.app_identities'::regclass),false)),
    ('no_direct_browser_policies', NOT EXISTS (SELECT 1 FROM pg_policies WHERE schemaname='public' AND tablename IN ('app_identities','workspaces','workspace_memberships'))),
    ('no_browser_table_privileges', NOT has_table_privilege('anon','public.app_identities','SELECT') AND NOT has_table_privilege('authenticated','public.app_identities','SELECT') AND NOT has_table_privilege('anon','public.workspaces','SELECT') AND NOT has_table_privilege('authenticated','public.workspaces','SELECT') AND NOT has_table_privilege('anon','public.workspace_memberships','SELECT') AND NOT has_table_privilege('authenticated','public.workspace_memberships','SELECT')),
    ('workspace_creation_actor_identity', EXISTS (SELECT 1 FROM information_schema.columns WHERE table_schema='public' AND table_name='workspaces' AND column_name='created_by_identity_id' AND data_type='uuid')),
    ('workspace_membership_identity', EXISTS (SELECT 1 FROM information_schema.columns WHERE table_schema='public' AND table_name='workspace_memberships' AND column_name='identity_id' AND data_type='uuid')),
    ('workspace_invitation_actor_identity', EXISTS (SELECT 1 FROM information_schema.columns WHERE table_schema='public' AND table_name='workspace_memberships' AND column_name='invited_by_identity_id' AND data_type='uuid')),
    ('identity_foreign_keys_restrictive', (SELECT count(*)=3 FROM pg_constraint WHERE contype='f' AND confrelid='public.app_identities'::regclass AND conrelid IN ('public.workspaces'::regclass,'public.workspace_memberships'::regclass) AND confdeltype='r')),
    ('updated_last_owner_trigger', EXISTS (SELECT 1 FROM pg_trigger WHERE tgrelid='public.workspace_memberships'::regclass AND tgname='workspace_memberships_last_owner_guard' AND NOT tgisinternal AND pg_get_triggerdef(oid) LIKE '%identity_id%')),
    ('obsolete_identity_columns_absent', NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_schema='public' AND ((table_name='workspaces' AND column_name='created_by_user_id') OR (table_name='workspace_memberships' AND column_name IN ('user_id','invited_by_user_id'))))),
    ('workspace_auth_uid_policies_absent', NOT EXISTS (SELECT 1 FROM pg_policies WHERE schemaname='public' AND tablename IN ('workspaces','workspace_memberships') AND (qual LIKE '%auth.uid%' OR with_check LIKE '%auth.uid%'))),
    ('workspace_auth_user_foreign_keys_absent', NOT EXISTS (SELECT 1 FROM pg_constraint WHERE contype='f' AND conrelid IN ('public.workspaces'::regclass,'public.workspace_memberships'::regclass) AND confrelid='auth.users'::regclass))
  ) s(check_name,passed)
),
brand_rel AS (SELECT b.id brand_id,b.workspace_id,lower(btrim(b.owner_email)) owner_key,b.owner_email IS NULL OR btrim(b.owner_email)='' empty_owner,NOT coalesce(b.owner_email ~* '^[^[:space:]@]+@[^[:space:]@]+[.][^[:space:]@]+$',false) unsupported_owner FROM public.brands b),
board_rel AS (SELECT b.id board_id,b.brand_id,b.workspace_id,lower(btrim(coalesce(nullif(b.owner_email,''),b.owner_id))) owner_key,coalesce(nullif(btrim(b.owner_email),''),nullif(btrim(b.owner_id),'')) IS NULL empty_owner,NOT coalesce(coalesce(nullif(btrim(b.owner_email),''),nullif(btrim(b.owner_id),'')) ~* '^[^[:space:]@]+@[^[:space:]@]+[.][^[:space:]@]+$',false) unsupported_owner,b.brand_core_snapshot IS NOT NULL has_snapshot,b.public_view_enabled FROM public.boards b),
member_rel AS (SELECT m.brand_id,lower(btrim(m.email)) identity_key,m.role,m.email IS NULL OR btrim(m.email)='' empty_identity,NOT coalesce(m.email ~* '^[^[:space:]@]+@[^[:space:]@]+[.][^[:space:]@]+$',false) unsupported FROM public.brand_members m),
share_rel AS (SELECT e.board_id,lower(btrim(e.email)) identity_key,e.role,e.email IS NULL OR btrim(e.email)='' empty_identity,NOT coalesce(e.email ~* '^[^[:space:]@]+@[^[:space:]@]+[.][^[:space:]@]+$',false) unsupported FROM public.board_editors e),
primary_owners AS (SELECT owner_key FROM brand_rel WHERE NOT empty_owner AND NOT unsupported_owner UNION SELECT owner_key FROM board_rel WHERE NOT empty_owner AND NOT unsupported_owner),
brand_members AS (SELECT DISTINCT identity_key FROM member_rel WHERE NOT empty_identity AND NOT unsupported),
qualifying_identities AS (SELECT owner_key identity_key FROM primary_owners UNION SELECT identity_key FROM brand_members),
board_only AS (SELECT DISTINCT s.identity_key FROM share_rel s WHERE NOT s.empty_identity AND NOT s.unsupported AND NOT EXISTS(SELECT 1 FROM qualifying_identities q WHERE q.identity_key=s.identity_key)),
visibility AS (SELECT DISTINCT b.owner_key workspace_owner,m.identity_key FROM member_rel m JOIN brand_rel b USING(brand_id) WHERE NOT b.empty_owner AND NOT b.unsupported_owner AND NOT m.empty_identity AND NOT m.unsupported AND m.identity_key<>b.owner_key),
identity_matches AS (SELECT q.identity_key,count(a.id)::bigint matches,count(a.id) FILTER(WHERE a.status='disabled')::bigint disabled FROM qualifying_identities q LEFT JOIN public.app_identities a ON a.canonical_email=q.identity_key GROUP BY q.identity_key),
brand_safe AS (SELECT b.* FROM brand_rel b WHERE NOT empty_owner AND NOT unsupported_owner),
board_safe AS (SELECT b.* FROM board_rel b LEFT JOIN brand_rel br ON br.brand_id=b.brand_id WHERE NOT b.empty_owner AND NOT b.unsupported_owner AND (b.brand_id IS NULL OR (br.brand_id IS NOT NULL AND br.owner_key=b.owner_key AND NOT br.empty_owner AND NOT br.unsupported_owner))),
access_risks AS (SELECT (SELECT count(*) FROM share_rel s WHERE EXISTS(SELECT 1 FROM visibility v WHERE v.identity_key=s.identity_key) AND NOT EXISTS(SELECT 1 FROM brand_members m WHERE m.identity_key=s.identity_key))::bigint expansion, (SELECT count(*) FROM member_rel WHERE empty_identity OR unsupported)::bigint loss),
blockers AS (
 SELECT
 (SELECT count(*) FROM schema_checks WHERE NOT passed)
 +(SELECT count(*) FROM public.app_identities)+(SELECT count(*) FROM public.workspaces)+(SELECT count(*) FROM public.workspace_memberships)+(SELECT count(*) FROM brand_rel WHERE workspace_id IS NOT NULL)+(SELECT count(*) FROM board_rel WHERE workspace_id IS NOT NULL)
 +(SELECT count(*) FROM brand_rel WHERE empty_owner OR unsupported_owner)+(SELECT count(*) FROM board_rel WHERE empty_owner OR unsupported_owner)
 +(SELECT count(*) FROM member_rel WHERE empty_identity OR unsupported)+(SELECT count(*) FROM share_rel WHERE empty_identity OR unsupported)
 +(SELECT count(*) FROM identity_matches WHERE matches>1 OR disabled>0)
 +(SELECT count(*) FROM board_rel b WHERE b.brand_id IS NOT NULL AND NOT EXISTS(SELECT 1 FROM brand_rel br WHERE br.brand_id=b.brand_id))
 +(SELECT count(*) FROM board_rel b JOIN brand_rel br ON br.brand_id=b.brand_id WHERE b.owner_key<>br.owner_key)
 +(SELECT expansion+loss FROM access_risks) AS n
),
checks(sort_group,sort_item,category,check_name,status,record_count,notes) AS (
 SELECT 1,row_number() OVER(ORDER BY check_name),'identity_bridge_schema',check_name,CASE WHEN passed THEN 'ok' ELSE 'blocked' END,CASE WHEN passed THEN 0 ELSE 1 END::bigint,'Exact post-BW-36.7R2 structural contract; mismatch blocks.' FROM schema_checks
 UNION ALL SELECT 2,1,'post_migration_state','existing_app_identities',CASE WHEN count(*)=0 THEN 'ok' ELSE 'blocked' END,count(*)::bigint,'Expected zero adoption; nonzero requires explicit review.' FROM public.app_identities
 UNION ALL SELECT 2,2,'post_migration_state','existing_workspaces',CASE WHEN count(*)=0 THEN 'ok' ELSE 'blocked' END,count(*)::bigint,'Expected zero adoption; nonzero is not labeled corrupt.' FROM public.workspaces
 UNION ALL SELECT 2,3,'post_migration_state','existing_workspace_memberships',CASE WHEN count(*)=0 THEN 'ok' ELSE 'blocked' END,count(*)::bigint,'Expected zero adoption.' FROM public.workspace_memberships
 UNION ALL SELECT 2,4,'post_migration_state','brands_already_assigned',CASE WHEN count(*)=0 THEN 'ok' ELSE 'blocked' END,count(*)::bigint,'Partial adoption blocks first automatic backfill.' FROM brand_rel WHERE workspace_id IS NOT NULL
 UNION ALL SELECT 2,5,'post_migration_state','boards_already_assigned',CASE WHEN count(*)=0 THEN 'ok' ELSE 'blocked' END,count(*)::bigint,'Partial adoption blocks first automatic backfill.' FROM board_rel WHERE workspace_id IS NOT NULL
 UNION ALL SELECT 2,6,'post_migration_state','disabled_application_identities',CASE WHEN count(*)=0 THEN 'ok' ELSE 'blocked' END,count(*)::bigint,'Disabled identities block matching projections.' FROM public.app_identities WHERE status='disabled'
 UNION ALL SELECT 2,7,'post_migration_state','orphaned_identity_references',CASE WHEN count(*)=0 THEN 'ok' ELSE 'blocked' END,count(*)::bigint,'Every Workspace identity reference must resolve.' FROM (SELECT created_by_identity_id x FROM public.workspaces UNION ALL SELECT identity_id FROM public.workspace_memberships UNION ALL SELECT invited_by_identity_id FROM public.workspace_memberships WHERE invited_by_identity_id IS NOT NULL) r LEFT JOIN public.app_identities a ON a.id=r.x WHERE a.id IS NULL
 UNION ALL SELECT 2,8,'post_migration_state','unexpected_partial_adoption',CASE WHEN count(*)=0 THEN 'ok' ELSE 'blocked' END,count(*)::bigint,'Any adopted catalog requires explicit review.' FROM (SELECT id FROM public.workspaces UNION ALL SELECT workspace_id FROM public.workspace_memberships UNION ALL SELECT workspace_id FROM brand_rel WHERE workspace_id IS NOT NULL UNION ALL SELECT workspace_id FROM board_rel WHERE workspace_id IS NOT NULL) x
 UNION ALL SELECT 3,n,'source_identity_inventory',name,CASE WHEN status='blocked' AND cnt=0 THEN 'ok' WHEN status='review' AND cnt=0 THEN 'info' ELSE status END,cnt,note FROM (VALUES
 (1,'brand_owner_relationships','info',(SELECT count(*)::bigint FROM brand_rel),'Typed relationship count.'),(2,'distinct_brand_owner_identities','info',(SELECT count(DISTINCT owner_key)::bigint FROM brand_rel),'Canonical lower-trim identities.'),(3,'board_owner_relationships','info',(SELECT count(*)::bigint FROM board_rel),'Typed relationship count.'),(4,'distinct_board_owner_identities','info',(SELECT count(DISTINCT owner_key)::bigint FROM board_rel),'Canonical lower-trim identities.'),(5,'brand_member_relationships','info',(SELECT count(*)::bigint FROM member_rel),'Existing grants.'),(6,'distinct_brand_member_identities','info',(SELECT count(DISTINCT identity_key)::bigint FROM member_rel),'Deduplicated canonical identities.'),(7,'board_share_relationships','info',(SELECT count(*)::bigint FROM share_rel),'Existing grants.'),(8,'distinct_board_share_identities','info',(SELECT count(DISTINCT identity_key)::bigint FROM share_rel),'Deduplicated canonical identities.'),(9,'empty_identities','blocked',(SELECT count(*)::bigint FROM brand_rel WHERE empty_owner)+(SELECT count(*) FROM board_rel WHERE empty_owner)+(SELECT count(*) FROM member_rel WHERE empty_identity)+(SELECT count(*) FROM share_rel WHERE empty_identity),'Must be zero.'),(10,'unsupported_identity_shapes','blocked',(SELECT count(*)::bigint FROM brand_rel WHERE unsupported_owner)+(SELECT count(*) FROM board_rel WHERE unsupported_owner)+(SELECT count(*) FROM member_rel WHERE unsupported)+(SELECT count(*) FROM share_rel WHERE unsupported),'Must be zero.'),(11,'normalized_duplicates_within_constraints','blocked',(SELECT count(*)::bigint FROM (SELECT brand_id,identity_key FROM member_rel GROUP BY 1,2 HAVING count(*)>1 UNION ALL SELECT board_id,identity_key FROM share_rel GROUP BY 1,2 HAVING count(*)>1)d),'Repeated ownership across entities is intentionally excluded.'),(12,'genuinely_ambiguous_authority','blocked',(SELECT count(*)::bigint FROM identity_matches WHERE matches>1),'Canonical authority must be unique.'),(13,'distinct_primary_owners','info',(SELECT count(*)::bigint FROM primary_owners),'One future default Workspace each.'),(14,'primary_owners_brand_only','info',(SELECT count(*)::bigint FROM primary_owners p WHERE EXISTS(SELECT 1 FROM brand_rel b WHERE b.owner_key=p.owner_key) AND NOT EXISTS(SELECT 1 FROM board_rel b WHERE b.owner_key=p.owner_key)),'Disjoint owner cohort.'),(15,'primary_owners_board_only','info',(SELECT count(*)::bigint FROM primary_owners p WHERE EXISTS(SELECT 1 FROM board_rel b WHERE b.owner_key=p.owner_key) AND NOT EXISTS(SELECT 1 FROM brand_rel b WHERE b.owner_key=p.owner_key)),'Disjoint owner cohort.'),(16,'primary_owners_both','info',(SELECT count(*)::bigint FROM primary_owners p WHERE EXISTS(SELECT 1 FROM brand_rel b WHERE b.owner_key=p.owner_key) AND EXISTS(SELECT 1 FROM board_rel b WHERE b.owner_key=p.owner_key)),'Disjoint owner cohort.')) v(n,name,status,cnt,note)
 UNION ALL SELECT 4,n,'projected_application_identities',name,CASE WHEN status='blocked' AND cnt=0 THEN 'ok' WHEN status='review' AND cnt=0 THEN 'info' ELSE status END,cnt,note FROM (VALUES
 (1,'primary_owner_identities_required','info',(SELECT count(*)::bigint FROM primary_owners),'Qualifying path.'),(2,'brand_member_identities_required','info',(SELECT count(*)::bigint FROM brand_members),'Qualifying path.'),(3,'brand_members_already_primary_owners','info',(SELECT count(*)::bigint FROM brand_members m JOIN primary_owners p ON p.owner_key=m.identity_key),'Overlap counted once.'),(4,'additional_non_owner_brand_members','info',(SELECT count(*)::bigint FROM brand_members m WHERE NOT EXISTS(SELECT 1 FROM primary_owners p WHERE p.owner_key=m.identity_key)),'Disjoint additional identities.'),(5,'board_only_collaborators_excluded','info',(SELECT count(*)::bigint FROM board_only),'No identity solely for a Board share.'),(6,'public_token_access_excluded','info',(SELECT count(*)::bigint FROM board_rel WHERE public_view_enabled),'Anonymous access creates no identity.'),(7,'total_distinct_application_identities','info',(SELECT count(*)::bigint FROM qualifying_identities),'Union of qualifying paths.'),(8,'existing_matching_application_identities','info',(SELECT count(*)::bigint FROM identity_matches WHERE matches=1),'Existing canonical matches.'),(9,'missing_application_identities_to_create','info',(SELECT count(*)::bigint FROM identity_matches WHERE matches=0),'Future insert projection.'),(10,'disabled_matching_identities','blocked',(SELECT coalesce(sum(disabled),0)::bigint FROM identity_matches),'Must be zero.'),(11,'canonical_email_collisions','blocked',(SELECT count(*)::bigint FROM identity_matches WHERE matches>1),'Must be zero.'),(12,'conflicting_partial_mappings','blocked',(SELECT count(*)::bigint FROM identity_matches WHERE matches>1 OR disabled>0),'Must be zero.'))v(n,name,status,cnt,note)
 UNION ALL SELECT 5,n,'projected_workspaces',name,CASE WHEN status='blocked' AND cnt=0 THEN 'ok' WHEN status='review' AND cnt=0 THEN 'info' ELSE status END,cnt,note FROM (VALUES
 (1,'distinct_safe_primary_owners','info',(SELECT count(*)::bigint FROM primary_owners),'Safe canonical owners.'),(2,'deterministic_default_workspaces_to_create','info',(SELECT count(*)::bigint FROM primary_owners),'Exactly one per distinct safe owner.'),(3,'existing_matching_workspace_candidates','blocked',(SELECT count(*)::bigint FROM public.workspaces),'Zero-adoption prerequisite.'),(4,'primary_owners_requiring_quarantine','blocked',(SELECT count(*)::bigint FROM brand_rel WHERE empty_owner OR unsupported_owner)+(SELECT count(*) FROM board_rel WHERE empty_owner OR unsupported_owner),'Unsafe owners.'),(5,'owner_collisions','blocked',(SELECT count(*)::bigint FROM identity_matches WHERE matches>1),'Must be zero.'),(6,'brands_for_projected_owner_workspaces','info',(SELECT count(*)::bigint FROM brand_safe),'Aggregate Brand placement.'),(7,'unbranded_boards_for_owner_workspace','info',(SELECT count(*)::bigint FROM board_safe WHERE brand_id IS NULL),'Owner placement.'),(8,'branded_boards_inheriting_brand_workspace','info',(SELECT count(*)::bigint FROM board_safe WHERE brand_id IS NOT NULL),'Brand inheritance.'),(9,'owners_with_brands_and_boards','info',(SELECT count(*)::bigint FROM primary_owners p WHERE EXISTS(SELECT 1 FROM brand_rel b WHERE b.owner_key=p.owner_key) AND EXISTS(SELECT 1 FROM board_rel b WHERE b.owner_key=p.owner_key)),'Owner cohort.'),(10,'owners_with_boards_only','info',(SELECT count(*)::bigint FROM primary_owners p WHERE EXISTS(SELECT 1 FROM board_rel b WHERE b.owner_key=p.owner_key) AND NOT EXISTS(SELECT 1 FROM brand_rel b WHERE b.owner_key=p.owner_key)),'Owner cohort.'),(11,'owners_with_brands_only','info',(SELECT count(*)::bigint FROM primary_owners p WHERE EXISTS(SELECT 1 FROM brand_rel b WHERE b.owner_key=p.owner_key) AND NOT EXISTS(SELECT 1 FROM board_rel b WHERE b.owner_key=p.owner_key)),'Owner cohort.'))v(n,name,status,cnt,note)
 UNION ALL SELECT 6,n,'projected_memberships',name,CASE WHEN status='blocked' AND cnt=0 THEN 'ok' WHEN status='review' AND cnt=0 THEN 'info' ELSE status END,cnt,note FROM (VALUES
 (1,'owner_memberships_to_create','info',(SELECT count(*)::bigint FROM primary_owners),'One accepted owner per default Workspace.'),(2,'minimal_visibility_memberships_to_create','info',(SELECT count(*)::bigint FROM visibility),'Least-privileged viewer visibility; Brand authorization remains in brand_members.'),(3,'brand_admins_requiring_visibility','info',(SELECT count(*)::bigint FROM member_rel WHERE role='admin'),'Existing Brand role unchanged.'),(4,'brand_editors_requiring_visibility','info',(SELECT count(*)::bigint FROM member_rel WHERE role='editor'),'Existing Brand role unchanged.'),(5,'brand_viewers_requiring_visibility','info',(SELECT count(*)::bigint FROM member_rel WHERE role='viewer'),'Existing Brand role unchanged.'),(6,'qualifying_identities_covered_by_owner','info',(SELECT count(*)::bigint FROM brand_members m JOIN primary_owners p ON p.owner_key=m.identity_key),'No duplicate membership for same Workspace.'),(7,'deduplicated_total_memberships','info',(SELECT count(*)::bigint FROM primary_owners)+(SELECT count(*) FROM visibility),'Typed owner plus visibility projections.'),(8,'board_only_collaborators_excluded','info',(SELECT count(*)::bigint FROM board_only),'Remain Board-only.'),(9,'public_token_access_excluded','info',(SELECT count(*)::bigint FROM board_rel WHERE public_view_enabled),'No membership.'),(10,'conflicting_projected_roles','blocked',0::bigint,'Owner wins over visibility within an owner Workspace.'),(11,'missing_identity_prerequisites','blocked',(SELECT count(*)::bigint FROM identity_matches WHERE matches>1 OR disabled>0),'Must be zero before writes.'),(12,'last_owner_invariant_readiness','ok',0::bigint,'Every projected Workspace receives exactly one accepted owner.'))v(n,name,status,cnt,note)
 UNION ALL SELECT 7,n,'projected_brand_assignments',name,CASE WHEN status='blocked' AND cnt=0 THEN 'ok' WHEN status='review' AND cnt=0 THEN 'info' ELSE status END,cnt,note FROM (VALUES (1,'total_reusable_brands','info',(SELECT count(*)::bigint FROM brand_rel),'All reusable Brands.'),(2,'brands_safe_for_assignment','info',(SELECT count(*)::bigint FROM brand_safe),'Safe owners.'),(3,'brands_already_assigned','blocked',(SELECT count(*)::bigint FROM brand_rel WHERE workspace_id IS NOT NULL),'Must be zero.'),(4,'brands_requiring_quarantine','blocked',(SELECT count(*)::bigint FROM brand_rel WHERE empty_owner OR unsupported_owner),'Must be zero.'),(5,'brands_with_missing_owners','blocked',(SELECT count(*)::bigint FROM brand_rel WHERE empty_owner),'Must be zero.'),(6,'brands_with_unsupported_owners','blocked',(SELECT count(*)::bigint FROM brand_rel WHERE unsupported_owner),'Must be zero.'),(7,'brands_with_ambiguous_owners','blocked',(SELECT count(*)::bigint FROM brand_rel b JOIN identity_matches i ON i.identity_key=b.owner_key WHERE i.matches>1),'Must be zero.'),(8,'brands_with_conflicting_workspace_state','blocked',(SELECT count(*)::bigint FROM brand_rel WHERE workspace_id IS NOT NULL),'Partial adoption.'),(9,'projected_brand_assignments','info',(SELECT count(*)::bigint FROM brand_safe WHERE workspace_id IS NULL),'Owner default Workspace.'))v(n,name,status,cnt,note)
 UNION ALL SELECT 8,n,'projected_board_assignments',name,CASE WHEN status='blocked' AND cnt=0 THEN 'ok' WHEN status='review' AND cnt=0 THEN 'info' ELSE status END,cnt,note FROM (VALUES (1,'total_boards','info',(SELECT count(*)::bigint FROM board_rel),'All Boards.'),(2,'branded_boards','info',(SELECT count(*)::bigint FROM board_rel WHERE brand_id IS NOT NULL),'Explicit associations only.'),(3,'unbranded_boards','info',(SELECT count(*)::bigint FROM board_rel WHERE brand_id IS NULL),'No inferred Brand.'),(4,'snapshot_only_unbranded_boards','info',(SELECT count(*)::bigint FROM board_rel WHERE brand_id IS NULL AND has_snapshot),'Snapshot remains unchanged.'),(5,'boards_without_brand_or_snapshot','info',(SELECT count(*)::bigint FROM board_rel WHERE brand_id IS NULL AND NOT has_snapshot),'Owner placement.'),(6,'branded_boards_safe_to_inherit','info',(SELECT count(*)::bigint FROM board_safe WHERE brand_id IS NOT NULL),'Inherit Brand Workspace.'),(7,'unbranded_boards_safe_for_owner','info',(SELECT count(*)::bigint FROM board_safe WHERE brand_id IS NULL),'Owner Workspace.'),(8,'boards_already_assigned','blocked',(SELECT count(*)::bigint FROM board_rel WHERE workspace_id IS NOT NULL),'Must be zero.'),(9,'boards_requiring_quarantine','blocked',(SELECT count(*)::bigint FROM board_rel b WHERE NOT EXISTS(SELECT 1 FROM board_safe s WHERE s.board_id=b.board_id)),'Must be zero.'),(10,'missing_brand_associations','blocked',(SELECT count(*)::bigint FROM board_rel b WHERE brand_id IS NOT NULL AND NOT EXISTS(SELECT 1 FROM brand_rel br WHERE br.brand_id=b.brand_id)),'Must be zero.'),(11,'board_brand_owner_mismatches','blocked',(SELECT count(*)::bigint FROM board_rel b JOIN brand_rel br ON br.brand_id=b.brand_id WHERE b.owner_key<>br.owner_key),'Must be zero.'),(12,'cross_workspace_relationship_risks','blocked',(SELECT count(*)::bigint FROM board_rel WHERE workspace_id IS NOT NULL),'Must be zero before initial assignment.'),(13,'projected_board_assignments','info',(SELECT count(*)::bigint FROM board_safe WHERE workspace_id IS NULL),'No Brand inference; snapshots unchanged.'))v(n,name,status,cnt,note)
 UNION ALL SELECT 9,n,'access_preservation',name,CASE WHEN status='blocked' AND cnt=0 THEN 'ok' WHEN status='review' AND cnt=0 THEN 'info' ELSE status END,cnt,note FROM (VALUES (1,'brand_owner_relationships_preserved','info',(SELECT count(*)::bigint FROM brand_rel),'Unchanged.'),(2,'brand_admin_relationships_preserved','info',(SELECT count(*)::bigint FROM member_rel WHERE role='admin'),'Unchanged.'),(3,'brand_editor_relationships_preserved','info',(SELECT count(*)::bigint FROM member_rel WHERE role='editor'),'Unchanged.'),(4,'brand_viewer_relationships_preserved','info',(SELECT count(*)::bigint FROM member_rel WHERE role='viewer'),'Unchanged.'),(5,'board_owner_relationships_preserved','info',(SELECT count(*)::bigint FROM board_rel),'Unchanged.'),(6,'board_editor_relationships_preserved','info',(SELECT count(*)::bigint FROM share_rel WHERE role='editor'),'Unchanged.'),(7,'board_viewer_relationships_preserved','info',(SELECT count(*)::bigint FROM share_rel WHERE role='viewer'),'Unchanged.'),(8,'board_only_collaborators_remaining_board_only','info',(SELECT count(*)::bigint FROM board_only),'Excluded.'),(9,'collaborators_independently_receiving_brand_visibility','info',(SELECT count(DISTINCT s.identity_key)::bigint FROM share_rel s JOIN brand_members m USING(identity_key)),'Qualify independently.'),(10,'public_token_boards_remaining_bounded','info',(SELECT count(*)::bigint FROM board_rel WHERE public_view_enabled),'One-Board state unchanged.'),(11,'potential_access_expansion_cases','blocked',(SELECT expansion FROM access_risks),'Must be zero.'),(12,'potential_access_loss_cases','blocked',(SELECT loss FROM access_risks),'Must be zero.'),(13,'relationships_incorrectly_projected_to_membership','blocked',(SELECT count(*)::bigint FROM board_only b JOIN visibility v ON v.identity_key=b.identity_key),'Must be zero.'),(14,'relationships_requiring_later_review','review',0::bigint,'No bounded product decision detected by this projection.'))v(n,name,status,cnt,note)
 UNION ALL SELECT 10,n,'backfill_projection',name,CASE WHEN status='blocked' AND cnt=0 THEN 'ok' WHEN status='review' AND cnt=0 THEN 'info' ELSE status END,cnt,note FROM (VALUES (1,'application_identities_to_insert','info',(SELECT count(*)::bigint FROM identity_matches WHERE matches=0),'Future write set.'),(2,'workspaces_to_insert','info',(SELECT count(*)::bigint FROM primary_owners),'Future write set.'),(3,'owner_memberships_to_insert','info',(SELECT count(*)::bigint FROM primary_owners),'Future write set.'),(4,'minimal_visibility_memberships_to_insert','info',(SELECT count(*)::bigint FROM visibility),'Future viewer write set.'),(5,'total_memberships_to_insert','info',(SELECT count(*)::bigint FROM primary_owners)+(SELECT count(*) FROM visibility),'Disjoint role projections.'),(6,'brands_to_assign','info',(SELECT count(*)::bigint FROM brand_safe WHERE workspace_id IS NULL),'Future write set.'),(7,'branded_boards_to_assign','info',(SELECT count(*)::bigint FROM board_safe WHERE brand_id IS NOT NULL AND workspace_id IS NULL),'Through Brand Workspace.'),(8,'unbranded_boards_to_assign','info',(SELECT count(*)::bigint FROM board_safe WHERE brand_id IS NULL AND workspace_id IS NULL),'Through owner Workspace.'),(9,'total_boards_to_assign','info',(SELECT count(*)::bigint FROM board_safe WHERE workspace_id IS NULL),'Disjoint branded/unbranded total.'),(10,'existing_rows_remaining_unchanged','info',(SELECT count(*)::bigint FROM brand_rel)+(SELECT count(*) FROM board_rel)+(SELECT count(*) FROM member_rel)+(SELECT count(*) FROM share_rel),'Typed source rows, not a global identity population.'),(11,'board_shares_remaining_unchanged','info',(SELECT count(*)::bigint FROM share_rel),'No share writes.'),(12,'brand_memberships_remaining_unchanged','info',(SELECT count(*)::bigint FROM member_rel),'No Brand grant writes.'),(13,'campaign_brand_snapshots_remaining_unchanged','info',(SELECT count(*)::bigint FROM board_rel WHERE has_snapshot),'No snapshot writes.'),(14,'public_token_states_remaining_unchanged','info',(SELECT count(*)::bigint FROM board_rel WHERE public_view_enabled),'No token writes.'),(15,'total_quarantine_records','blocked',(SELECT count(*)::bigint FROM brand_rel WHERE empty_owner OR unsupported_owner)+(SELECT count(*) FROM board_rel b WHERE NOT EXISTS(SELECT 1 FROM board_safe s WHERE s.board_id=b.board_id)),'Typed quarantined entities.'),(16,'total_blocking_anomalies',CASE WHEN (SELECT n FROM blockers)=0 THEN 'ok' ELSE 'blocked' END,(SELECT n::bigint FROM blockers),'Disjoint genuine blockers; review-only relationships are excluded.'))v(n,name,status,cnt,note)
 UNION ALL SELECT 11,1,'final_readiness','workspace_backfill_readiness',CASE WHEN n=0 THEN 'ok' ELSE 'blocked' END,n::bigint,'Even ok authorizes only preparation of a separately reviewed transactional backfill; it does not execute or automatically approve BW-36.8.' FROM blockers
)
SELECT category,check_name,status,record_count,notes FROM checks ORDER BY sort_group,sort_item,check_name;
