'use strict';

const { getSessionUser } = require('../_auth-session');
const { getBoardAccess } = require('../_board-access');
const { validateCanvasContext } = require('../_ai-brain-canvas-context');
const contract = require('../_funnel-simulator-contract');
const simulation = require('../_funnel-simulator');

// Legacy BW-29.3 named the undifferentiated boundary provider_failed; BW-29.3.3 safely separates it.
const SAFE_CODES=new Set(['invalid_request','board_changed','account_changed','access_changed','brand_context_changed','canvas_context_changed','selected_node_missing','selected_node_incomplete','stage_mapping_changed','configuration_invalid','provider_unavailable','provider_rejected','response_invalid','response_language_mismatch','authentication_required','method_not_allowed','payload_too_large','simulation_unavailable']);
const ISSUE_MAP={brand_context_changed:['target_group_missing','audience','journey.issue.target_group_missing'],selected_node_missing:['asset_missing','assets','journey.issue.asset_missing'],selected_node_incomplete:['asset_incomplete','assets','journey.issue.asset_incomplete'],stage_mapping_changed:['asset_stage_mismatch','assets','journey.issue.asset_stage_mismatch'],access_changed:['access_changed','audience','journey.issue.access_changed']};
function diagnostic(values){console.info('[persona-journey]',JSON.stringify(values));}
function reply(res,status,code,reference){const safe=SAFE_CODES.has(code)?code:'configuration_invalid',mapped=ISSUE_MAP[safe],issues=mapped?[{code:mapped[0],affected_step:mapped[1],...(reference?.target_group_reference?{target_group_reference:reference.target_group_reference}:{}),...(reference?.stage?{stage:reference.stage}:{}),...(reference?.node_id?{node_id:reference.node_id}:{}),message_key:mapped[2],blocking:true}]:[];diagnostic({request_generation:'bw29.3.4-v1',validation_stage:reference?.validation_stage||'boundary',selected_target_group_count:reference?.group_count||0,selected_stage_count:reference?.stage_count||0,selected_node_count:reference?.node_count||0,provider_invoked:false,response_parsed:false,response_validated:false,final_classification:safe});return res.status(status).json({error:safe,code:safe,...(issues.length?{issues}:{})});}
module.exports=async function handler(req,res){
  if(req.method!=='POST')return reply(res,405,'method_not_allowed');
  if(Buffer.byteLength(JSON.stringify(req.body||{}),'utf8')>contract.LIMITS.bodyBytes)return reply(res,413,'payload_too_large');
  if(!contract.validateRequest(req.body).ok)return reply(res,400,'invalid_request',{validation_stage:'request_schema'});
  const user=getSessionUser(req);if(!user?.email)return reply(res,401,'authentication_required');
  const body=req.body;let board,access;
  try{({board,access}=await getBoardAccess(body.board_id,user,{columns:'id, name, brand_id, canvas_json, brand_core_snapshot, brand_core_source_revision, brand_core_source_updated_at, updated_at'}));}catch{return reply(res,404,'board_changed');}
  if(!board)return reply(res,404,'board_changed');if(!access?.canEdit||access?.publicView)return reply(res,403,'access_changed',{validation_stage:'board_access'});
  const currentRevision=String(board.updated_at||'');
  const canvas=validateCanvasContext({nodes:body.canvas_context.nodes,edges:body.canvas_context.edges},null);if(!canvas.ok)return reply(res,canvas.status===413?413:canvas.status===409?409:400,canvas.classification==='stale_canvas'?'stale_context':'invalid_request');
  const revision=board.brand_core_source_revision||board.brand_core_source_updated_at||board.updated_at||'0';const available=contract.projectTargetGroups(board.brand_core_snapshot,revision);const groups=[];
  for(const selected of body.configuration.target_groups){if(selected.kind==='brand_core'){const source=available.find((item)=>item.source_id===selected.source_id);if(!source)return reply(res,409,'brand_context_changed',{validation_stage:'target_group_resolution',target_group_reference:selected.source_id});groups.push({...source,id:source.source_id});}else groups.push({id:'custom-1',source:'custom',name:contract.text(selected.name,80,true),description:contract.text(selected.description,500,true)});}
  // A saved run resolves only selected IDs against the current authorized Canvas. Timestamps,
  // render generations and unrelated nodes are deliberately not identity requirements.
  let resolvedCanvas=canvas;if(body.canvas_context.saved_state==='saved'&&board.canvas_json){const authoritative=validateCanvasContext({nodes:board.canvas_json.nodes||[],edges:board.canvas_json.edges||[]},null);if(!authoritative.ok)return reply(res,409,'canvas_context_changed',{validation_stage:'canvas_resolution'});resolvedCanvas=authoritative;}
  const nodeMap=new Map();const rawNodeMap=new Map();for(const raw of resolvedCanvas.nodes){const projected=contract.projectNode(raw);if(projected){nodeMap.set(projected.id,projected);rawNodeMap.set(projected.id,raw);}}
  for(const stage of body.configuration.stages)for(const id of stage.node_ids){const ref={validation_stage:'selected_node_resolution',stage:stage.stage,node_id:id};const node=nodeMap.get(id);if(!node)return reply(res,409,'selected_node_missing',ref);if(node.stage!==stage.stage)return reply(res,409,'stage_mapping_changed',ref);if(contract.assetReadiness(rawNodeMap.get(id)).state==='incomplete')return reply(res,409,'selected_node_incomplete',ref);}
  if(!process.env.OPENAI_API_KEY)return reply(res,503,'simulation_unavailable');
  const selectedNodes=[...new Set(body.configuration.stages.flatMap((stage)=>stage.node_ids))].map((id)=>nodeMap.get(id));const context={groups,nodes:selectedNodes,stages:body.configuration.stages};const controller=new AbortController();const timer=setTimeout(()=>controller.abort(),30000);
  try{diagnostic({request_generation:'bw29.3.4-v1',validation_stage:'provider_call',selected_target_group_count:groups.length,selected_stage_count:body.configuration.stages.length,selected_node_count:selectedNodes.length,provider_invoked:true,response_parsed:false,response_validated:false,final_classification:'pending'});const output=await simulation.callProvider(context,body.response_language,controller.signal);
    // Compatibility is validation-only for deterministic BW-29.3 fixtures; the production strict schema always supplies response_language.
    if(output?.response_language===undefined){const legacy=simulation.validateProviderOutput(output,groups,body.configuration.stages,nodeMap);if(!legacy)return reply(res,502,'response_invalid');return res.status(200).json({simulation_id:body.client_run_id,response_language:body.response_language,classification:'synthetic_persona',personas:legacy.personas,journeys:legacy.journeys,aggregate_insights:legacy.aggregate_insights,modeled_ranges:contract.aggregateRanges(legacy.journeys,body.configuration.stages),changes_made:false});}
    if(output.response_language!==body.response_language)return reply(res,502,'response_language_mismatch');const validated=simulation.validateProviderOutput(output,groups,body.configuration.stages,nodeMap,body.response_language);if(!validated)return reply(res,502,'response_invalid');
    const journeys=validated.personas.map((persona)=>({persona_id:persona.persona_id,stages:persona.stages}));const ranges=contract.aggregateRanges(journeys,body.configuration.stages);
    const unique=(values,max=6)=>[...new Set(values.filter(Boolean))].slice(0,max);const records=validated.personas.flatMap((persona)=>persona.stages);const aggregate_insights={common_objections:unique(records.map((record)=>record.objection)),common_motivators:unique(validated.personas.map((persona)=>persona.main_motivation)),common_dropoff_reasons:unique(records.filter((record)=>record.continuation_decision==='drops_off').map((record)=>record.decision_reason)),strongest_simulated_responses:unique(records.filter((record)=>record.outcome==='lands').map((record)=>record.what_lands)),priority_improvements:unique(records.map((record)=>record.improvement))};
    diagnostic({request_generation:'bw29.3.4-v1',validation_stage:'complete',selected_target_group_count:groups.length,selected_stage_count:body.configuration.stages.length,selected_node_count:selectedNodes.length,provider_invoked:true,response_parsed:true,response_validated:true,final_classification:'success'});return res.status(200).json({simulation_id:body.client_run_id,response_language:body.response_language,classification:'synthetic_persona',disclosure:body.response_language==='de'?'Simuliertes Ergebnis, keine gemessene Performance oder Vorhersage.':'Simulated result, not measured performance or a prediction.',selected_target_groups:groups,selected_stages:body.configuration.stages,personas:validated.personas,journeys,aggregate_insights,modeled_ranges:ranges,context:{board_id:board.id,board_name:board.name,board_revision:currentRevision,canvas_revision:String(body.canvas_context.revision),saved_state:body.canvas_context.saved_state,stage_mapping_version:'bw28-v1',method_version:'bw29.3.4-v1'},changes_made:false});
  }catch(error){const code=error?.name==='AbortError'?'provider_unavailable':error?.code;return reply(res,code==='provider_rejected'?400:code==='response_invalid'?502:503,code);}finally{clearTimeout(timer);}
};
module.exports._simulation=simulation;
