'use strict';

const { getSessionUser } = require('../_auth-session');
const { getBoardAccess } = require('../_board-access');
const { validateCanvasContext } = require('../_ai-brain-canvas-context');
const contract = require('../_funnel-simulator-contract');
const simulation = require('../_funnel-simulator');
const crypto = require('crypto');

// Legacy BW-29.3 named the undifferentiated boundary provider_failed; BW-29.3.3 safely separates it.
const SAFE_CODES=new Set(['invalid_request','board_changed','account_changed','access_changed','brand_context_changed','canvas_context_changed','selected_node_missing','selected_node_incomplete','stage_mapping_changed','configuration_invalid','provider_unavailable','provider_rejected','response_invalid','response_language_mismatch','authentication_required','method_not_allowed','payload_too_large','simulation_unavailable']);
const ISSUE_MAP={brand_context_changed:['target_group_missing','audience','journey.issue.target_group_missing'],selected_node_missing:['asset_missing','assets','journey.issue.asset_missing'],selected_node_incomplete:['asset_incomplete','assets','journey.issue.asset_incomplete'],stage_mapping_changed:['asset_stage_mismatch','assets','journey.issue.asset_stage_mismatch'],access_changed:['access_changed','audience','journey.issue.access_changed']};
function diagnostic(values){console.info('[persona-journey]',JSON.stringify(values));}
function requestId(){return crypto.randomBytes(4).toString('hex').toUpperCase();}
function reply(res,status,code,reference={}){const safe=SAFE_CODES.has(code)?code:'configuration_invalid',mapped=ISSUE_MAP[safe],issues=reference.issues||(mapped?[{code:mapped[0],affected_step:mapped[1],...(reference.target_group_reference?{target_group_reference:reference.target_group_reference}:{}),...(reference.stage?{stage:reference.stage}:{}),...(reference.node_id?{node_id:reference.node_id}:{}),message_key:mapped[2],blocking:true}]:[]),classification=reference.classification||safe,id=reference.requestId||requestId(),phase=reference.validation_phase||reference.validation_stage||'boundary';const diagnostics={validation_phase:phase,authentication_passed:!!reference.authentication_passed,board_access_passed:!!reference.board_access_passed,target_groups_resolved:!!reference.target_groups_resolved,stages_resolved:!!reference.stages_resolved,nodes_resolved:!!reference.nodes_resolved,nodes_ready:!!reference.nodes_ready,provider_invoked:!!reference.provider_invoked,provider_status_category:reference.provider_status_category||'not_invoked',provider_output_validated:!!reference.provider_output_validated};diagnostic({request_id:id,code:safe,classification,...diagnostics});return res.status(status).json({error:safe,code:safe,classification,requestId:id,diagnostics,...(issues.length?{issues}:{})});}
module.exports=async function handler(req,res){
  const id=requestId(),base={requestId:id};if(req.method!=='POST')return reply(res,405,'method_not_allowed',base);
  if(Buffer.byteLength(JSON.stringify(req.body||{}),'utf8')>contract.LIMITS.bodyBytes)return reply(res,413,'payload_too_large',base);
  if(!contract.validateRequest(req.body).ok)return reply(res,400,'invalid_request',{...base,validation_phase:'request_schema'});
  const user=getSessionUser(req);if(!user?.email)return reply(res,401,'authentication_required',base);base.authentication_passed=true;
  const body=req.body;let board,access;
  try{({board,access}=await getBoardAccess(body.board_id,user,{columns:'id, name, brand_id, canvas_json, brand_core_snapshot, brand_core_source_revision, brand_core_source_updated_at, updated_at'}));}catch{return reply(res,404,'board_changed',base);}
  if(!board)return reply(res,404,'board_changed',base);if(!access?.canEdit||access?.publicView)return reply(res,403,'access_changed',{...base,validation_phase:'board_access'});base.board_access_passed=true;
  const currentRevision=String(board.updated_at||'');
  const canvas=validateCanvasContext({nodes:body.canvas_context.nodes,edges:body.canvas_context.edges},null);if(!canvas.ok)return reply(res,canvas.status===413?413:canvas.status===409?409:400,canvas.classification==='stale_canvas'?'stale_context':'invalid_request',{...base,validation_phase:'canvas_resolution'});
  const revision=board.brand_core_source_revision||board.brand_core_source_updated_at||board.updated_at||'0';const available=contract.projectTargetGroups(board.brand_core_snapshot,revision);
  // A saved run resolves only selected IDs against the current authorized Canvas. Timestamps,
  // render generations and unrelated nodes are deliberately not identity requirements.
  let resolvedCanvas=canvas;if(body.canvas_context.saved_state==='saved'&&board.canvas_json){const authoritative=validateCanvasContext({nodes:board.canvas_json.nodes||[],edges:board.canvas_json.edges||[]},null);if(!authoritative.ok)return reply(res,409,'canvas_context_changed',{...base,validation_phase:'canvas_resolution'});resolvedCanvas=authoritative;}
  const evaluation=contract.evaluateConfiguration(body.configuration,available,resolvedCanvas.nodes);if(!evaluation.isRunnable){const issue=evaluation.actionableIssues[0],classification=issue?.code==='target_group_missing'?'target_group_unresolved':issue?.code||'execution_contract_mismatch';return reply(res,409,'configuration_invalid',{...base,validation_phase:issue?.affected_step||'configuration_evaluation',classification,issues:evaluation.actionableIssues,target_groups_resolved:!evaluation.actionableIssues.some(x=>x.affected_step==='target-groups'),stages_resolved:!evaluation.actionableIssues.some(x=>x.affected_step==='stages'),nodes_resolved:!evaluation.actionableIssues.some(x=>x.code==='asset_missing'),nodes_ready:!evaluation.actionableIssues.some(x=>x.code==='asset_incomplete')});}const groups=evaluation.normalizedTargetGroups;base.target_groups_resolved=base.stages_resolved=base.nodes_resolved=base.nodes_ready=true;
  const nodeMap=new Map(evaluation.resolvedSelectedAssets.map(node=>[node.id,node]));
  if(!process.env.OPENAI_API_KEY)return reply(res,503,'simulation_unavailable',{...base,validation_phase:'provider_preflight'});
  const selectedNodes=[...new Set(body.configuration.stages.flatMap((stage)=>stage.node_ids))].map((id)=>nodeMap.get(id));const context={groups,nodes:selectedNodes,stages:body.configuration.stages};const controller=new AbortController();const timer=setTimeout(()=>controller.abort(),30000);
  try{diagnostic({request_id:id,request_generation:'bw29.3.5-v1',validation_phase:'provider_call',selected_target_group_count:groups.length,selected_stage_count:body.configuration.stages.length,selected_node_count:selectedNodes.length,provider_invoked:true,response_parsed:false,response_validated:false,final_classification:'pending'});const output=await simulation.callProvider(context,body.response_language,controller.signal);
    // Compatibility is validation-only for deterministic BW-29.3 fixtures; the production strict schema always supplies response_language.
    if(output?.response_language===undefined){const legacy=simulation.validateProviderOutput(output,groups,body.configuration.stages,nodeMap);if(!legacy)return reply(res,502,'response_invalid');return res.status(200).json({requestId:id,simulation_id:body.client_run_id,response_language:body.response_language,classification:'synthetic_persona',personas:legacy.personas,journeys:legacy.journeys,aggregate_insights:legacy.aggregate_insights,modeled_ranges:contract.aggregateRanges(legacy.journeys,body.configuration.stages),changes_made:false});}
    if(output.response_language!==body.response_language)return reply(res,502,'response_language_mismatch');const validated=simulation.validateProviderOutput(output,groups,body.configuration.stages,nodeMap,body.response_language);if(!validated)return reply(res,502,'response_invalid');
    const journeys=validated.personas.map((persona)=>({persona_id:persona.persona_id,stages:persona.stages}));const ranges=contract.aggregateRanges(journeys,body.configuration.stages);
    const unique=(values,max=6)=>[...new Set(values.filter(Boolean))].slice(0,max);const records=validated.personas.flatMap((persona)=>persona.stages);const aggregate_insights={common_objections:unique(records.map((record)=>record.objection)),common_motivators:unique(validated.personas.map((persona)=>persona.main_motivation)),common_dropoff_reasons:unique(records.filter((record)=>record.continuation_decision==='drops_off').map((record)=>record.decision_reason)),strongest_simulated_responses:unique(records.filter((record)=>record.outcome==='lands').map((record)=>record.what_lands)),priority_improvements:unique(records.map((record)=>record.improvement))};
    diagnostic({request_id:id,validation_phase:'complete',authentication_passed:true,board_access_passed:true,target_groups_resolved:true,stages_resolved:true,nodes_resolved:true,nodes_ready:true,provider_invoked:true,provider_status_category:'2xx',provider_output_validated:true,code:'success',classification:'synthetic_persona'});return res.status(200).json({requestId:id,simulation_id:body.client_run_id,response_language:body.response_language,classification:'synthetic_persona',disclosure:body.response_language==='de'?'Simuliertes Ergebnis, keine gemessene Performance oder Vorhersage.':'Simulated result, not measured performance or a prediction.',selected_target_groups:groups,selected_stages:body.configuration.stages,personas:validated.personas,journeys,aggregate_insights,modeled_ranges:ranges,context:{board_id:board.id,board_name:board.name,board_revision:currentRevision,canvas_revision:String(body.canvas_context.revision),saved_state:body.canvas_context.saved_state,stage_mapping_version:'bw28-v1',method_version:'bw29.3.5-v1'},changes_made:false});
  }catch(error){const code=error?.name==='AbortError'?'provider_unavailable':error?.code;return reply(res,code==='provider_rejected'?400:code==='response_invalid'?502:503,code,{...base,validation_phase:'provider_response',provider_invoked:true,provider_status_category:error?.providerStatus?`${Math.floor(error.providerStatus/100)}xx`:'unavailable'});}finally{clearTimeout(timer);}
};
module.exports._simulation=simulation;
